### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by sjmatta** [cflint/CFLint#132]
I'm curious if you guys have looked into rules related to code style, such as indentation or where the curly braces are opened (same line or next). I've done a couple of false starts toward implementing this myself and wanted to know if you had any suggestions. Thanks!

**Comment by ryaneberly** [comment]
Indentation might be a challenge. The current lint plugins present the
structure of the code, not the underlying source.

However, it is reasonable to make some of these decisions by looking at the
antlr parse tree directly.

I'll see if I can throw together an example to get you started.

**Comment by ryaneberly** [comment]
@sjmatta  take a look at 
BracketsStyleChecker in 
https://github.com/cflint/CFLint/compare/dev...vistoexample?expand=1

this takes a deep dive into antlr and visiting parse trees.  It's not especially clean.

**Comment by sjmatta** [comment]
Awesome thank you! I will dive in very soon. Used up my free time today getting another linter version out the door but I will have some tomorrow.

**Comment by ryaneberly** [comment]
closing for now
