### ISSUE TITLE
Finding UNUSED_METHOD_ARGUMENT appears too often

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#143]
Hi,

i ran CFLint on a large project. I'm still sorting out all the tests but I stumbled upon `UNUSED_METHOD_ARGUMENT` 
I use Coldspring framework where it's allowed to have a 'init' method in the CFC that is being called as a constructor. References to other CFCs may be passed in. My CFC now looks like:

<cfcomponent output="false">

	<cffunction name="init" access="public" hint="constructor" output="false" returntype="Service">
		<cfargument name="otherService" type="any">

		<cfset variables.otherSrv = Arguments.otherService>

		<cfreturn this>
	</cffunction>

	<cffunction name="myMethod" access="public" hint="calculates" output="false" returntype="numeric">
		<cfargument name="numFirst" type="numeric" required="true">
		<cfargument name="numSecond" type="numeric" required="true">

		<cfset local.iSum = Arguments.numFirst + Arguments.numSecond>

		<cfreturn local.iSum>
	</cffunction>

</cfcomponent>

I call CFLint in a console
`java -jar CFLint-0.6.1-all.jar -includeRule UNUSED_METHOD_ARGUMENT -json -file Service.cfc -logerror -v`

The results file lists three findings:

    "line" : "4",
    "message" : "Argument otherService is not used in function init, consider removing it.",

    "line" : "12",
    "message" : "Argument numFirst is not used in function myMethod, consider removing it.",

    "line" : "13",
    "message" : "Argument numSecond is not used in function myMethod, consider removing it.",

Actually all three times the argument is used. First it's assigned to a variable in a larger scope to be used outside of the function. Second and third time it's used "regularly" - referenced in the `Arguments` scope. I didn't delve deepy enough into your code to understand how you test if an argument is being used, but I saw your `\test\` scripts never access the arguments scope.

Thank you for your effort and keep up the good work,
Bernhard

**Comment by justinmclean** [comment]
I'll take a look in the next couple of days. You mind trying "arguments" rather than "Arguments". It may just be a simple case issue in the code.

**Comment by justinmclean** [comment]
Fixed, tested and checked into dev branch. Code wasn't checking for arguments scope. Would you mind running over your code and seeing that it fixes the issue?

**Comment by bardware** [comment]
I see what you did there :)
I does not yet work for me out of the box. In the `element` function are you putting the content of the name attribute into the `methodArguments` map without careing for case.
In the `useIdentifier` function you call `get` on the map with the lowercase name. So the variable is not found and still marked as not used.
Change this one line to

    final String name = element.getAttributeValue("name").toLowerCase();
and we're done here.

Thank you!

**Comment by justinmclean** [comment]
fixed and checked into develop

**Comment by bardware** [comment]
works. Thank you!
