### ISSUE TITLE
AVOID_USING_CFINCUDE_TAG spelling

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#144]
I wanted to run every available test one after another on my Coldfusion project. To find out which tests are available I parsed your `cflint.definition.json` file. When I was browsing the results I was surprised this one test brought zero results.
It is because there's an `l` missing in the test's `message => code`

**Comment by justinmclean** [comment]
Fixed spelling error in JSON file in dev branch.

**Comment by bardware** [comment]
looks good
