### ISSUE TITLE
difference between output styles -text and -json

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#146]
When I have CFLint output it's results in text format I get more information than when I get JSON results.

Example

    <cffunction name="varNotDeclared" returntype="numeric" hint="VAR_NOT_DECLARED" output="false">

        <cfset undeclaredVar = "Hello World">

        <cfreturn 1>
    </cffunction>

I run `java -jar CFLint-0.6.1-all.jar -includeRule MISSING_VAR -text` and receive: `Variable:'undeclaredVar' in function: varNotDeclared`
I run: `java -jar CFLint-0.6.1-all.jar -includeRule MISSING_VAR -json` and receive:
`    "message" : "Variable undeclaredVar is not declared with a var statement.",
    "variable" : "undeclaredVar",
    "expression" : "undeclaredVar"
`

Can you please change the JSON output to also include the name of the function where the variable is not declared?

**Comment by justinmclean** [comment]
Fixed in dev branch. Also added to XML output.

**Comment by bardware** [comment]
I see a function member in the JSON output and it's filled correctly in `MISSING_VAR` and `AVOID_USING_CFINCLUDE_TAG`.
It might also be set in `UNUSED_METHOD_ARGUMENT`

**Comment by justinmclean** [comment]
Fixed and added function name to a few other rules that it might be helpful in.

**Comment by bardware** [comment]
FUNCTION_TOO_COMPLEX and ARG_HINT_MISSING might set the function member also.

**Comment by justinmclean** [comment]
Fixed along with a couple of others.

**Comment by bardware** [comment]
looks good

**Comment by bardware** [comment]
This [change](https://github.com/cflint/CFLint/commit/6c1b074b2f2e2a5ac84ed698a75f6f1a25a56e37#diff-4e600e01d2dc7ab9afa818d516377dfb) has not made it into the 0.7.0 release

**Comment by ryaneberly** [comment]
Oh.  I see that now.  Thanks for pointing that out.

**Comment by ryaneberly** [comment]
it's in 0.7.1
