### ISSUE TITLE
VAR_ALLCAPS_NAME handles scope

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#147]
Me again :)

I run test `VAR_ALLCAPS_NAME` on a CFC and get results like:

    Message:Variable LOCAL should not be upper case.
    Message:Variable SESSION should not be upper case.

It maybe should ignore the notation of the scopes `LOCAL`, `THIS`, `VARIABLES`,  `ARGUMENTS` and care for the actual name.

**Comment by justinmclean** [comment]
IMO scopes should be in lower case but I can see that some people way want to upper case CGI or URL or possibly other scopes. When I have some time later this week I'll break the rule into two, one to check for the scope and the other the variable name. That way you can turn off the scope one if you have lots of uppercase scopes.

**Comment by justinmclean** [comment]
Added new rule "SCOPE_ALL_CAPS" so you can check both errors and/or turn off SCOPE_ALL_CAPS if you want.
