### ISSUE TITLE
Propsal: Drop "Variable x should be longer than 3 characters" warning

### ISSUE THREAD

**Issue by atuttle** [cflint/CFLint#151]
For example, popular CFML MVC framework [fw/1](https://github.com/framework-one/fw1) uses the variable `rc` (short for Request Context) heavily.

If the intention is to stop people from using single letter variables for iterators, e.g. in `for (var i = 0;` then I think I could get onboard with that... I would just say it should be a minimum of two, not three. If that wasn't the intention of the rule, I'd be curious to hear what the intention was.

Here's a list of all of the places where variable name lengths are being checked.

https://github.com/cflint/CFLint/search?utf8=%E2%9C%93&q=longer+than+characters

**Comment by justinmclean** [comment]
This like all rules this is configurable, you can exclude the rule altogether or you can set the minimum number of characters.

**Comment by atuttle** [comment]
I'm using CFLint through SublimeLinter. I guess I'll get in touch with them to find out how to configure it. Thanks.

**Comment by justinmclean** [comment]
I've not used SublimeLinter can you pass any parameters through to the jar?

**Comment by justinmclean** [comment]
I've not used SublimeLinter can you pass any parameters through to the jar?

**Comment by atuttle** [comment]
Guess we'll find out. :)

**Comment by atuttle** [comment]
So yes, I can include a `cflintrc.xml` file in my project to set rules, but they don't document the supported XML.

See you have a [wiki page](https://github.com/cflint/CFLint/wiki/Include-Exclude-Rules-Using-External-XML-File) with some samples on it, but one thing that's not represented there is setting a value like minimum or maximum variable length.

**Comment by ryaneberly** [comment]
Include the rule, copied from cflint.definition.json
to .cflint        (json form of the config file).

put it in the "rule" array.

     {  
         "rule": [
         {
           "name": "VariableNameChecker",
           "className": "VariableNameChecker",
           "message": [
             {
               "code": "VAR_INVALID_NAME",
               "severity": "INFO"
             },
             {
               "code": "VAR_ALLCAPS_NAME",
               "severity": "INFO"
             },
             {
               "code": "SCOPE_ALLCAPS_NAME",
               "severity": "INFO"
             },
             {
               "code": "VAR_TOO_SHORT",
               "severity": "INFO",
               "messageText": "Variable ${variable} should be longer than ${MinLength} characters."
             },
             {
               "code": "VAR_TOO_LONG",
               "severity": "INFO"
             },
             {
               "code": "VAR_TOO_WORDY",
               "severity": "INFO"
             },
             {
               "code": "VAR_IS_TEMPORARY",
               "severity": "INFO"
             },
             {     
               "code": "VAR_HAS_PREFIX_OR_POSTFIX",
               "severity": "INFO"
             }
           ],
           "parameter": [
             {
               "name": "MinLength",
               "value": "4"
             },
             {
               "name": "MaxLength",
               "value": "20"
             },
             {
               "name": "MaxWords",
               "value": "4"
             }
           ]
         }
       ]  
     }

**Comment by denuno** [comment]
As easy as it is for users to change this, I'm in favor of having the default min be 2 characters, as I think there are too many common 2 char things like "rc", or valid things like "id", and thus a lot of folk will want to edit/disable this rule, versus being able to use the default.

**Comment by ryaneberly** [comment]
closing for now.

**Comment by natewaite** [comment]
Your up
Late
