### ISSUE TITLE
unused-local-variable ignores variable usage inside of <cfquery> (QoQ)

### ISSUE THREAD

**Issue by sjmatta** [cflint/CFLint#153]
I get an "unused-local-variable" warning for "getWorkOrder" even though it is used in the Query of Queries:
```coldfusion
<cffunction name="getSiteWorkOrders" output="no" returntype="query">
  <cfset var getWorkOrder = "" />
  <cfquery name="getWorkOrder" datasource="#application.workOrderDS#">
    SELECT * FROM WORKORDER WHERE SITEID='123' AND LOCATION='1234' AND WONUM='1'
  </cfquery>

  <cfset var qoqGetWorkOrder = "" />
  <cfquery name="qoqGetWorkOrder" dbtype="query">
    SELECT * FROM getWorkOrder
  </cfquery>

  <cfreturn qoqGetWorkOrder />
</cffunction>

<cfdump var="#getSiteWorkOrders()#" />
```

_Local variable getWorkOrder is not used in function getSiteWorkOrders, consider removing it. (line 2, column 3)_

**Comment by ryaneberly** [comment]
Looks like this is already fixed in the dev branch.

**Comment by ryaneberly** [comment]
0.7.1 has it.

https://oss.sonatype.org/#nexus-search;quick~cflint
it will propagate to 
http://mvnrepository.com/artifact/com.github.cflint/CFLint
in a couple days.

**Comment by zspitzer** [comment]
I'm getting UNUSED_LOCAL_VARIABLE

**Local variable q_two is not used in function testQuery, consider removing it.**

`<cffunction name="testQuery" access="public" returntype="any" output="false">
    	<CFargument name="event" type="any">
        <cfscript>
			var q_one = queryNew("id,name", "integer,varchar");
			var q_two = queryNew("id,name", "integer,varchar");
			var q_three = "";
		</cfscript>
        <cfquery name="q_three" dbtype="query">
            select 	q_one.id, q_two.name
            from 	q_one, q_two
            where 	q_one.id = q_two.id
        </cfquery>
    </cffunction>`

**Comment by zspitzer** [comment]
can you reopen this @ryaneberly ?
