### ISSUE TITLE
cfmodule

### ISSUE THREAD

**Issue by morgdenn** [cflint/CFLint#176]
Hi,

Are you able to explain why there is the rule "AVOID_USING_CFMODULE_TAG"?  Is there something wrong with them?  Searching the web i've not been able to find anyone having an opinion either way.

I never use cfmodule myself but my colleague loves them.

Also, thanks for CFLint, you have made my life a lot better.

thanks,
Morgan.

**Comment by ryaneberly** [comment]
It is a matter of preference to some degree.  You could disable that rule if you wish.  There is some related discussion here : https://github.com/cflint/CFLint/issues/145

**Comment by jerronjames** [comment]
I came across this blog yesterday as well https://www.raymondcamden.com/2006/01/11/Ask-a-Jedi-CFINCLUDE-versus-CFMODULE/
