### ISSUE TITLE
Named arguments in functions

### ISSUE THREAD

**Issue by edswifa** [cflint/CFLint#182]
I am getting Errors for named arguments in method calls. Can this be excluded or is it an issue.

Variable crid is not declared with a var statement. Use var or the local scope, or otherwise clarify the scope
In file CallPackageDao.cfc, line 247
In **********\object\cps\CallPackageDao.cfc
In function FindAllCallRates()
At line : 247
Expression: crid

The code parsed is shown below.
<cfscript>
	var callRate = getServiceLocator().get("object.cps.CallRate");
	callRate.init(crid = CallRateId, newName = Name, newDescription = Description);
	ArrayAppend(result, callRate);
</cfscript>

I even get it with argumentcollection.

**Comment by ryaneberly** [comment]
I'm pretty certain this is fixed in the master branch.  I added a test for this case in dev and it doesn't flag 'crid'

**Comment by edswifa** [comment]
I'm definitley using CFLint-0.7.3-all.jar which was built from the master branch 2 days ago.
The error is showing for any code where I use a named argument.

Here is an example for argumentcollection.
`<cffunction name="FindCallPackageByProduct" access="public" output="false" returntype="object.cps.CallPackage">
		<cfargument name="ispCode" type="string" required="true">
		<cfargument name="productCode" type="string" required="true">
		
		<cfscript>
			var result = variables.dao.FindCallPackageByProduct(argumentcollection = arguments);
		</cfscript>

		<cfreturn result />
	</cffunction>`

`<issue abbrev="MV" category="CFLint" message="MISSING_VAR" id="MISSING_VAR" severity="ERROR">
<location message="Variable argumentcollection is not declared with a var statement." variable="argumentcollection" line="27" column="58" function="FindCallPackageByProduct" fileName="CallPackageFacade.cfc" file="C:\***********\object\cps\CallPackageFacade.cfc">
<Expression>
<![CDATA[argumentcollection]]>
</Expression>
</location>
</issue>
`

**Comment by ryaneberly** [comment]
Hmm, I'm having trouble duplicating it on my workstation.   And the travis build didn't pick it up with the new test added.  https://travis-ci.org/cflint/CFLint/branches

does this source file flag any MISSING_VAR for you?
https://github.com/cflint/CFLint/blob/dev/src/test/resources/com/cflint/tests/VarScoper/namedArgs.cfc

**Comment by edswifa** [comment]
I'm running from the command line.

java -jar CFLint-0.7.3-all.jar -ui

Variable crid is not declared with a var statement. Use var or the local scope, or otherwise clarify the scope


In file namedArgs.cfc, line 4
In C:\Users\swifta\Documents\Downloads\namedArgs.cfc
In function x()
At line : 4
Expression: crid

**Comment by ryaneberly** [comment]
found it.  sorry it took a while.

**Comment by edswifa** [comment]
Just tried to build the dev branch and got a failure so I cant check your fix.

[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/swifta/Documents/Downloads/CFLint-dev/src/main/java/com/cflint/tools/CFLintFilter.java:[11,17] package
 org.slf4j does not exist
[ERROR] /C:/Users/swifta/Documents/Downloads/CFLint-dev/src/main/java/com/cflint/tools/CFLintFilter.java:[12,17] package
 org.slf4j does not exist
[ERROR] /C:/Users/swifta/Documents/Downloads/CFLint-dev/src/main/java/com/cflint/tools/CFLintFilter.java:[19,22] cannot
find symbol
  symbol:   class Logger
  location: class com.cflint.tools.CFLintFilter
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.600 s
[INFO] Finished at: 2016-06-30T13:10:26+01:00
[INFO] Final Memory: 16M/48M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.3:compile (default-compile) on project C
FLint: Compilation failure: Compilation failure:
[ERROR] /C:/Users/swifta/Documents/Downloads/CFLint-dev/src/main/java/com/cflint/tools/CFLintFilter.java:[11,17] package
 org.slf4j does not exist
[ERROR] /C:/Users/swifta/Documents/Downloads/CFLint-dev/src/main/java/com/cflint/tools/CFLintFilter.java:[12,17] package
 org.slf4j does not exist
[ERROR] /C:/Users/swifta/Documents/Downloads/CFLint-dev/src/main/java/com/cflint/tools/CFLintFilter.java:[19,22] cannot
find symbol
[ERROR] symbol:   class Logger
[ERROR] location: class com.cflint.tools.CFLintFilter
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by edswifa** [comment]
Ignore my last message.
I got it to build after deleting the whole directory and performing another clean install.

The issue is resolved, no longer reporting var scope error for named arguments.

Thanks for your help.
