### ISSUE TITLE
writeDump arguments not recognised correctly

### ISSUE THREAD

**Issue by jevans-gp** [cflint/CFLint#183]
When using `writeDump`, you specify the variable to dump by writing `writeDump(var = local.a)`, however this causes CFLint to falsely report:

![image](https://cloud.githubusercontent.com/assets/12134783/17059307/7182289e-501c-11e6-8177-74f4f2fcc664.png)

**Comment by ryaneberly** [comment]
Hi, Thanks for reporting this.  It is fixed in the dev branch #182
