### ISSUE TITLE
configfile excludes rules

### ISSUE THREAD

**Issue by morgdenn** [cflint/CFLint#185]
I would like to use my config file to exclude only the rule "FUNCTION_TYPE_ANY".

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<config>
	<excludes code="FUNCTION_TYPE_ANY" />
</config>`

It looks like this wont work until I also exclude "FUNCTION_TYPE_MISSING".  

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<config>
	<excludes code="FUNCTION_TYPE_ANY" />
	<excludes code="FUNCTION_TYPE_MISSING" />
</config>`

I can see in "CFLint/src/main/resources/cflint.definition.xml" they are both part of the same ruleImpl.   Do you have to exclude all the rules in a ruleImpl to have them excluded?

I'm currently using version 0.7.3

thanks,
Morgan.

(These rules aren't my exact requirements, just a simplified version for testing).

**Comment by ryaneberly** [comment]
It is a bit strange, I know, but I think the following will work.

    <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <config>
    <ruleImpl name="FunctionTypeChecker" className="FunctionTypeChecker">
        <message code="FUNCTION_TYPE_MISSING">
                <severity>WARNING</severity>
        </message>
        <message code="FUNCTION_TYPE_ANY">
                <severity>INFO</severity>
        </message>
    </ruleImpl>
    <excludes code="FUNCTION_TYPE_ANY" />
    </config>

see https://github.com/cflint/CFLint/wiki/Include-Exclude-Rules-Using-External-XML-File

or use the excludes filter file cflintexclude.json
see https://github.com/cflint/CFLint/wiki/Are-There-Any-Recipes-Out-There%3F

It will pick up cflintexclude.json on the classpath, or you can pass it as a command line arg:
-filterFile some/path/cflintexclude.json

Our documentation needs some attention.

**Comment by ryaneberly** [comment]
includes and excludes now work as expected.
