### ISSUE TITLE
Doesn't seem to be checking missing_var on cfscript cfcs

### ISSUE THREAD

**Issue by aaronsnyder** [cflint/CFLint#186]
I've been using CFLint (running the jar directly) and am able to verify that it will find missing var's in standard .cfc files. However, when testing on a .cfc file that is entirely cfscript, it doesn't seem to find my missing var's. 

Here's the command I'm running (in case it helps): 

`java -jar CFLint-0.7.3-all.jar -file /[webroot]/cfc/functions.cfc | grep -i 'missing_var'`

I don't see anything in the docs that leads me to believe that cfscript isn't supported. Any thoughts on what I'm missing here?

CFLint version: 0.7.3

**Comment by ryaneberly** [comment]
It should work with pure cfscript components.  I added a test to confirm that.  It's working.  Can you share the code snippet that doesn't flag the missing var?

**Comment by aaronsnyder** [comment]
Hey @ryaneberly, thanks for the quick reply!

After you confirmed that CFLint should infact be checking varscoping in CFSCRIPT CFCs, I set out to try to figure out why mine was being left out. I've built a test file that reflects the breaky parts of the CFC in my codebase. 

After I found this, I thought, "well there's probably a better way for us to do *that*!", but nonetheless, having a method like poorlyWrittenFunction() in a CFC file seems to prevent CFLint from reporting any issues on anything else in that file. It's as if CFLint becomes distracted by the awful, and forgets why it's even there. 

In my testing, it seems that all components of poorlyWrittenFunction() are required to reproduce the bug, hopefully this is helpful in diagnosing, should you decide to fix it.

Thanks!

Aaron

`
ccomponent  {

	public void function leakMemory(leak_modifier) {
		leaky_variable = leak_modifier;
		leakier_variable = leaky_variable * 2;

		return leaky_variable * leakier_variable;
	}

	public void function poorlyWrittenFunction() {
		writeDump('
			<img style="width:100%;float:left;" src="#request.imagefolder#/#application.SiteInfo.site_foldername#/404.jpg">
		');
	}
}
`

**Comment by ryaneberly** [comment]
Ok, there was a bug.  The Jericho Parser sees a &lt;img/&gt; and assumes it has to parse CFML.  I changed the code to parse cfscript if it finds a "component" ahead of that first "element" (or there are no elements at all -- which was supported by the old code).

**Comment by ryaneberly** [comment]
Thanks for the great sample

**Comment by aaronsnyder** [comment]
Awesome, thanks @ryaneberly!
