### ISSUE TITLE
New rule for specifying structure key names in quotation marks

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#198]
Can we add a new rule, that would check for whether keys for structures declared with `{}` are placed in quotation marks? So:

```
// not compliant
var myStruct = {
    myKey = "myValue"
};

//compliant
var myStruct = {
    "myKey" = "myValue"
};
```

The rationale for this would be that when using quotation marks, ColdFusion will keep the case of letters in the key, which is often useful when outputting the structure for languages that care about case---like JavaScript. Without the quotation marks, all keys will be uppercased.

**Comment by ryaneberly** [comment]
@mpaluchowski , thanks.  I added your suggestion:

```
    {
      "name": "StructKeyChecker",
      "message": [
        {
          "code": "UNQUOTED_STRUCT_KEY",
          "messageText": "Unquoted struct key ${variable} is not case-sensitive.  Quoting it is recommended.",
          "severity": "WARNING"
        }
      ],
      "parameter": [
        
      ]
    }    
```
