### ISSUE TITLE
Rules reporting missing hints should work with script-style code

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#199]
The three rules:

* Function is missing a hint.
* Component is missing a hint.
* Argument is missing a hint.

work only when a component is in CFML. Can they be extended to work with script code too?

**Comment by ryaneberly** [comment]
@mpaluchowski , good suggestion.  It looks like functions can be hinted in 3 ways in cfscript.

* a hint attribute
* @hint in a multiline comment
* the entire multiline comment is a hint.
?
Do you agree

**Comment by mpaluchowski** [comment]
Yes, agree :)

**Comment by ryaneberly** [comment]
@mpaluchowski ,
  this is implemented.   Note: the only valid way to hint arguments in cfscript seems to be javadoc style.
