### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by timbeadle** [cflint/CFLint#219]
It's Open Source Gratitude Day, so thank you @ryaneberly and the other contributors for making CFLint 😄

**Comment by ryaneberly** [comment]
Thanks @timbeadle .

**Comment by mjclemente** [comment]
Just want to tack on my appreciation as well. Thanks so much @ryaneberly for all the work you put into this awesome project.

**Comment by ryaneberly** [comment]
thanks!
