### ISSUE TITLE
"if" without an "else" triggers "Nothing to parse" warning

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#222]
The following code will cause CFLint to produce a "Nothing to parse" warning:

```coldfusion
component {
    public void function foo() {
        if (something) {
            doSomething();
        }
    }
}
```

while the following code will _not_:

```coldfusion
component {
    public void function foo() {
        if (something) {
            doSomething();
        } else {
            doSomethingElse();
        }
    }
}
```

The warnings multiply, so if a component has 5 instances of an `if` clause without an `else`, it'll trigger 5 "Nothing to parse" warnings.

**Comment by ryaneberly** [comment]
@mpaluchowski , Thanks.  I cannot duplicate this issue with the latest code, but I don't think the PARSE_NOTHING is a useful warning regardless.  I disabled it (dev branch)

**Comment by mpaluchowski** [comment]
@denuno's a303ef4 commit to `dev` seems to have fixed it. I was just waiting for it to merge to `main`.

**Comment by ryaneberly** [comment]
Got it. Thanks!
