### ISSUE TITLE
Duplicate "Temporary variable could be named better" warnings

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#223]
The following code:

```coldfusion
component {
    function foo() {
        var tempStruct = {};
        doSomething(tempStruct);
        tempStruct.foo = "bar";
    }
}
```

Will produce the warning "Temporary variable tempStruct could be named better." **3 times**, one for each of the occurrences of the variable `tempStruct`.

My expectation would be that the warning be triggered only once, for the line `var tempStruct = {};` where the variable is declared.

**Comment by ryaneberly** [comment]
fixed
