### ISSUE TITLE
GPG error on mvn clean install

### ISSUE THREAD

**Issue by btudor** [cflint/CFLint#23]
Keep getting a MojoExecutionException error due to Maven not being able to grab dependency: org.apache.maven.plugins:maven-gpg-plugin

**Comment by jjames967** [comment]
I've looked into this... it's set up as: 


			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-gpg-plugin</artifactId>
				<version>1.5</version>
				<executions>
					<execution>
						<id>sign-artifacts</id>
						<phase>verify</phase>
						<goals>
							<goal>sign</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

When I execute "mvn clean install" it doesn't generate signed files.  It only runs when I do "mvn verify". So I'm wondering why it's asking people who don't have gpg installed for it to be installed.

**Comment by jjames967** [comment]
My plan is to redo how the build is deployed. Hopefully it will remove any further isses.
