### ISSUE TITLE
parse error "can't look backwards more than one token in this stream"

### ISSUE THREAD

**Issue by abons** [cflint/CFLint#24]
var user = userservice\["getuser"\]();  --doesn't work
var user = userservice.getuser();     --works

The above 2 lines are both fine syntax. But the first line gives the parse error "can't look backwards more than one token in this stream". I can't use the 2nd line, because I use a variable within the brackets.

Is it possible to add my own excludeRule?
For instance with a regular expression \[.*\]\(\)

**Comment by ryaneberly** [comment]
fixed in antlr4 branch..  hopefully releasing soon.
