### ISSUE TITLE
Using 'function' as shorthand structure key causes a parsing error

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#249]
The following code:

```coldfusion
component {
  function foo() {
    var bar = {
      function = ''
    };
  }
}
```

causes a parsing error, where the log output only shows `null` and the resulting `cflint-result.xml` is empty. This is because of `function` used as a structure key in this shorthand notation.

The same code, formed as below, doesn't cause any issues:

```coldfusion
component {
  function foo() {
    var bar.function = '';
  }
}
```

**Comment by ryaneberly** [comment]
fixed in cfparser 2.4.3
