### ISSUE TITLE
Variable Prefix and Postfix - More dynamic

### ISSUE THREAD

**Issue by isaac-mercieca** [cflint/CFLint#254]
I have just started to introduce this static code analysis tool to a project which follows certain conventions such as a prefix to each variable name depending on the type for instance string variables are prefixed with 'str'. I know that this can be done by creating a custom rule. However, I was wondering if it would be useful to the project and also possible to make this rule parameter and thus including a new dynamic feature.

Thanks in advance.

**Comment by ryaneberly** [comment]
Are you talking about "[Hungarian notation](https://en.wikipedia.org/wiki/Hungarian_notation)"?

**Comment by isaac-mercieca** [comment]
Yes or more less it is very similar. As by making this more dynamic one can enforce certain naming conventions.

**Comment by ryaneberly** [comment]
I believe this should work for you now.   You can set up the RequiredVariableNamePrefix parameter for the Variable name checker, or pass
-DVariableNameChecker.RequiredVariableNamePrefix=str,b,etc

on the command line
