### ISSUE TITLE
unsused local variable rule does not handle cfinclude

### ISSUE THREAD

**Issue by isaac-mercieca** [cflint/CFLint#255]
Hi,

Although the usage if cfinclude is not very good practice especially within a function, I noticed that when checking whether a local variable is used or not this does not handle accessing the variable from a separate page included via the cfinclude tag.

Regards,
Isaac

**Comment by ryaneberly** [comment]
Isaac, that is a good point.   We may get around to implementing that at some time.  pull requests welcome.  :-)

**Comment by ryaneberly** [comment]
PR merged.
https://github.com/cflint/CFLint/pull/264
