### ISSUE TITLE
Does not see argument as used when it is used in brackets inside of function.

### ISSUE THREAD

**Issue by sdurette** [cflint/CFLint#257]
The following code uses the variable, but cflint states that the argument should be removed because it isn't used.

```
01	private void function updateBucket(
02		required struct data,
03		required string cmc,
04		required string wca,
05		required array searchRange,
06		required numeric value,
07		required array lookUp
08	)
09		output="false"
10		hint="I updated regular bucket counters"
11	{
12		var idx = -1;
13		var i = 0;
14		for (i = 1; i <= ArrayLen(searchRange); i += 1) {
15			if (value >= searchRange[i][1] && value <= searchRange[i][2]) {
16				idx = i;
17				break;
18			}
19		}
20
21		if (idx > 0) {
22			data.district[ARGUMENTS.lookUp[idx]] += 1;
23			data.cmc[cmc][ARGUMENTS.lookUp[idx]] += 1;
24			data.wca[wca][ARGUMENTS.lookUp[idx]] += 1;
25		}
26	}
```
Receives the following errors:
* Argument cmc is not used in function consider removing it
* Argument lookup is not used in function consider removing it
* Argument wca is not used in function consider removing it

As you can see, Argument cmc is used on line 23 inside []. Argument lookup is used in lines 22-24. Argument wca is used in line 24.

Thanks and please let me know if you need more information.
Steve

**Comment by sdurette** [comment]
Also, apparently it isn't just with brackets.  The following is another example where it doesn't see it.

```
01  private Boolean function regexCheck(
02        required string regex,
03        required string toCheck
04  )
05        output=false
06        hint="I compare the regex to the value to check."
07  {
08        var myRet = false;
09  
10        myRet = (refind(ARGUMENTS.regex, ARGUMENTS.toCheck)) ? True : False;
11  
12        return myRet;
13  }
```
Returns the following errors:
* 1 Argument regex is not used in function, consider removing it
* 1 Argument tocheck is not used in function, consider removing it

Both are there on line 10,

**Comment by ryaneberly** [comment]
Good catches @sdurette .   Thank you.  It looks like member expressions and ternary expressions were two places where the process was not drilling down into sub expressions.  Those are fixed. (v1.1.0 in dev)
