### ISSUE TITLE
Parse error for method calls with certain names including contains and import.

### ISSUE THREAD

**Issue by isaac-mercieca** [cflint/CFLint#258]
In cases where the method has a certain name a parse error is being generated.

<cfif idSet.contains(strId)>
.... do something
</cfif>

In certain cases one can rename the method however as displayed above in cases when the method is a native Java method this is not the case.

Regards,
Isaac

**Comment by ryaneberly** [comment]
fixed in cfparser dev branch.  It should be part of the next release.
