### ISSUE TITLE
Default Rules merging with config.xml

### ISSUE THREAD

**Issue by msp1kpj** [cflint/CFLint#260]
plugin-error Message code: AVOID_USING_CFDUMP_TAG is not configured correctly.at line 1 col 1
plugin-error Message code: AVOID_USING_CFABORT_TAG is not configured correctly.at line 1 col 1
plugin-error Message code: ARG_VAR_MIXED is not configured correctly.at line 1 col 1
plugin-error Message code: METHOD_INVALID_NAME is not configured correctly.at line 1 col 1
plugin-error Message code: METHOD_IS_TEMPORARY is not configured correctly.at line 1 col 1

With release 1.0.1 Have had to add additional Message rules to my cflintconfig.xml. I have been using the cflint.definition.json file to help recreate these rule. It seems like the default rules and messages are not merging together with the rule overrides. I tries copying the cflint.definition.json file and make my modification but I am not able to use that file to import. 

**Does Not Work**
"java.exe" -jar "CFLint-1.0.1-all.jar" -e -stdout -file Service.cfc -xml -filterFile "cflintexclude.json" -configfile "cflint.definition.json"
Unable to load config file. Unrecognized field "rules" (class com.cflint.config.CFLintConfig), not marked as ignorable (6 known properties: "output", "inheritParent", "excludes", "includes", "rule", "inheritPlugins"])
 at [Source: java.io.FileInputStream@3159c4b8; line: 2, column: 13] (through reference chain: com.cflint.config.CFLintConfig["rules"])

**Works but Does Not Merge rules**
"java.exe" -jar "CFLint-1.0.1-all.jar" -e -stdout -file Service.cfc -xml -filterFile "cflintexclude.json" -configfile "cflintconfig.xml"

**Comment by ryaneberly** [comment]
@msp1kpj ,  I believe it is fixed. Thank you.  Do you mind confirming?

**Comment by ryaneberly** [comment]
.. in the dev branch.
