### ISSUE TITLE
Identifier cfcatch is global, referencing in a CFC or function should be avoided.

### ISSUE THREAD

**Issue by vellian1** [cflint/CFLint#265]
I don't believe there's another way to get an error message from a <cftry> block outside of cfscript syntax, so shouldn't this be an exception?  Should CFCs not handle errors?

**Comment by ryaneberly** [comment]
It sounds like this is a bug in CFLint.  I'm surprised we haven't run into this before.  Can you get a short code sample.

**Comment by vellian1** [comment]
<cfcomponent>
      <cffunction name="myFunction" hint="My function">
            <cftry>
                  
                  <cfcatch type="any">
                        <cfreturn "Error: #CFCATCH.Message#">
                  </cfcatch>
            </cftry>
            <cfreturn "Success">
      </cffunction>
<cfcomponent>

**Comment by ryaneberly** [comment]
@vellian1 Thanks, it is fixed in the dev branch.

**Comment by vellian1** [comment]
Thanks!
