### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by morgdenn** [cflint/CFLint#268]
Hi, I've started playing around with installing CFLint with NPM.  I have the initial setup working but I thought I'd check with you before I go any further.    Are you happy for me to pursue this?

The main purpose for me is to make it easier to use with Sublime linter, Gulp and a pre-commit hook in GIT.   My next step would be to add some documentation and link back to your project.  

You can see the details here: [https://www.npmjs.com/package/cflint](https://www.npmjs.com/package/cflint)

thanks,
Morgan Dennithorne

**Comment by ryaneberly** [comment]
It's ok by me.  The easier the entry points for the community, the better.
