### ISSUE TITLE
Unclear error messages: Error in plugin, 0

### ISSUE THREAD

**Issue by mjclemente** [cflint/CFLint#269]
I'm seeing some strange behavior when using 1.1.0, from the master branch (it appears it may be related to use of underscores). I'll do my best to describe it, and provide a screenshot of the resulting output.

I'm including the errors thrown for two files; the same basic two errors are being thrown for each:
* _Error in plugin_
* _0_

For the _Error in plugin_, the expression referenced is `variables._.reverse(categoryList)`. No expression, line, or function is referenced for the _0_ error.

Possibly related to these, I'm also get the following errors: 
* _Message code: METHOD_ALLCAPS_NAME is not configured correctly._"
* _Message code: METHOD_TOO_SHORT is not configured correctly._

Is this an issue with my configuration or related to cflint? Thanks for any help or insight you can provide.

(In the first instance, it's a file in which I am using [underscoreCFC](http://russplaysguitar.github.io/UnderscoreCF/), and in the second, it's a FW/1 method. 

![image](https://cloud.githubusercontent.com/assets/5348419/26262163/dc297e6e-3ca1-11e7-949e-049ebb658ce1.png)

**Comment by ryaneberly** [comment]
cfparser does not know how to parse the underscore.   I will look into that.

**Comment by mjclemente** [comment]
Thanks! Sorry for the bother; as I've said before, love the project. Let me know if there's anything that I can do to help or clarify further.

**Comment by ryaneberly** [comment]
No problem at all.  Thanks for the continued contributions.

**Comment by ryaneberly** [comment]
@mjclemente  could you test against dev.  I cannot duplicate your issue.   If you still see it, could you provide a code sample.

**Comment by mjclemente** [comment]
Sure. Happy to.

When I went to install the dev version, I got a build error:

```
[INFO]
[INFO] --- maven-war-plugin:2.2:war (default-war) @ CFLint ---
[INFO] Packaging webapp
[INFO] Assembling webapp [CFLint] in [/Users/matthew/www/tools/CFLint-dev/target/CFLint-1.1.0]
[INFO] Processing war project
[INFO] Webapp assembled in [129 msecs]
[INFO] Building war: /Users/matthew/www/tools/CFLint-dev/target/CFLint-1.1.0.war
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 29.029 s
[INFO] Finished at: 2017-06-22T06:36:32-04:00
[INFO] Final Memory: 32M/588M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.2:war (default-war) on project CFLint: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

I feel like I should probably be able to figure out and correct this, but I'm a complete novice when it comes to Maven. Is there a change I can make to run the build successfully?

**Comment by mjclemente** [comment]
Sorry, just saw the updated instructions on installing (https://github.com/cflint/CFLint/wiki/How-Do-I-Install-This-Tool%3F). I'll try that route to see if it resolves the issue.

**Comment by mjclemente** [comment]
Okay, ran the build via Gradle. It says "BUILD SUCCESSFUL" at the end. However, I can't find the executable`cflint`. (There's no `target` or `appassembler`, folders, as there used to be following a Maven install. Not sure how to proceed.

**Comment by denuno** [comment]
Maven should work again, plus I cut out some loggers that shouldn't be
needed and we're causing some extraneous output.

-Den

**Comment by mjclemente** [comment]
Thanks. That fixed the build error.

I built CFLint from the latest dev, but the parsing issue is still occurring for me. 

I put together some code to reproduce it: https://github.com/mjclemente/cflint-underscore-test

Please let me know if there's more that I can do, or if there's any more information that I can provide.

**Comment by ryaneberly** [comment]
ValidNames checker has an issue with the underscore.   It should be fixed.

**Comment by mjclemente** [comment]
Awesome! Just downloaded from the dev branch and ran it. Worked perfectly! 

Thanks guys; this project is amazing.

**Comment by ryaneberly** [comment]
@mjclemente .  Thanks for testing it.
