### ISSUE TITLE
We need this to run for Visual Studio Code also.

### ISSUE THREAD

**Issue by sosensible** [cflint/CFLint#270]
Visual Studio Code is on the rise and a great free editor. Our whole team is using this tool and hearing others are converting to it also.

**Comment by jevans-gp** [comment]
I assume you were using this on Sublime through SublimeLinter?  it's more that VS Code needs to support this kind of thing than CFLint needs to support VS Code

**Comment by ryaneberly** [comment]
@sosensible, If someone wants to tackle the VSC integration, I will help where I can.   I don't use VSC myself, but some of my colleagues are picking it up
