### ISSUE TITLE
Findbugs XML output creates <?xml...?> tag twice

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#271]
... therefore import into TeamCity (and I assume other tools) fails.

```
<?xml version="1.0" encoding="UTF-8" ?>
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<BugCollection sequence="0" release="" version="1.1.0" xmlns:sets="http://exslt.org/sets">
<Project projectName=""/>
</BugCollection>
```

This is on the current master branch.

**Comment by TheRealAgentK** [comment]
This problem seems to stem from the XSL transformer not omitting the XML declaration properly. Fix incoming soon.

**Comment by ryaneberly** [comment]
merged.  thanks for the PR
