### ISSUE TITLE
cflint --version returns error

### ISSUE THREAD

**Issue by sdurette** [cflint/CFLint#28]
After finally figuring out where the compiled files and bat files were, it will process correctly, but using the command cflint --version (or cflint -version) returns the following error:
Exception in thread "main" java.lang.NullPointerException
        at com.cflint.Version.getVersion(Version.java:23)
        at com.cflint.main.CFLintMain.main(CFLintMain.java:102)

CFLint 0.2.0, Windows 7 (64bit), Java 1.8.0_25

**Comment by ryaneberly** [comment]
Thanks for noticing that.  
Not many folks are building from source.  Congratulations.

Version.java wasn't updated when the package naming structure was changed and the project was moved from my personal github account to github.com/cflint.

I fixed it.  -version should work now.
