### ISSUE TITLE
Working on CFLint

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#288]
Hey @ryaneberly - for all the previous change I made, I always just run a full build and played with the XSLT/Findbugs output through running it actually from command line.

Now with some of the Java changes I'm looking into doing that's a bit annoying. I was just wondering how your development setup looks like to get some benefit of using proper IDE features like breakpoints and debugging? Do you have a custom main entry class you're using to trigger CFLint runs inside of an IDE (in IntelliJ) with arguments you want etc?

**Comment by TheRealAgentK** [comment]
In a similar spirit - would you maybe be keen to host something like a 1hr intro session into the depths of cflint for people who are interested to contribute more towards the core, too?

**Comment by ryaneberly** [comment]
@TheRealAgentK ,  Good question.   
I personally use Eclipe with the Buildship Gradle plugin.  Just import 'an existing gradle project' and you are good to go.  I believe you will have the same import project experience with IntelliJ.

I would be happy to host a session.   Could you suggest agenda items, and best times.  I'm in US-EST (GMT-5)

**Comment by TheRealAgentK** [comment]
Oh yeah, importing the project in IntelliJ is fine and triggering a maven build to create the jars etc too, also running the unit tests. I just struggle to run it interactively from IntelliJ so that I can break and step into the execution.

**Comment by TheRealAgentK** [comment]
EST is New York, isn't it?

So, if it was only for the two of us, it seems that your late afternoon/evening would work really well for me. I work from home most days and I'm really flexible when I work for clients and when I do other things, so usually anything between 7am and 9pm in my time, I can make work.

http://www.worldtimeserver.com/meeting-planner-times.aspx?&L0=NZ&Day=11&Mon=6&Y=2017&L1=US-NY&L2=&L3=&L4=&L5=&L6=&L7=

**Comment by TheRealAgentK** [comment]
From an agenda point of of view, what I'd be interested in is:

- Day to day development flow
- Understanding the ties between CF Parser, CF Lint
- Following the flow through the code - maybe let's take a single CFC and see how the libraries analyse various problems
- How to and where to start making specific improvements to various areas:
-- Fixing parsing issues
-- Ignore rules mechanism
-- Output creation

Does that make sense?

**Comment by ryaneberly** [comment]
Sounds good.
   Maybe review the plugin framework, and how rules are reported.

**Comment by TheRealAgentK** [comment]
Cool, let me know when you could make some time and I'll try to make that work on my end.

**Comment by ryaneberly** [comment]
@TheRealAgentK 
  I'll see what works when I get back from travelling next week.

  With respect to IntelliJ, did you try importing it as a gradle project, not maven.

**Comment by ryaneberly** [comment]
Join up on slack if you can.
https://cflint.slack.com/

As far as a meetup, how about 9PM Monday or Tuesday (6/26,6/27) EST.   That would be 1PM Tuesday or Wednesday your time in NZ.

**Comment by TheRealAgentK** [comment]
I can make either work just fine on my end.

**Comment by isaac-mercieca** [comment]
@ryaneberly I am interested into including cflint into a project. I was
wondering whether if it would be possible to attend one of the sessions
please?

**Comment by TheRealAgentK** [comment]
@isaac-mercieca It'll happen Mon 26th, 9pm EST.

We'll run it on Zoom.us - I will post the link to the room 30-60 mins before here and on the CFML Slack and on the CFLint Slack.

**Comment by TheRealAgentK** [comment]
@isaac-mercieca I think that'll be in the middle of the night or very early morning for you in Malta. Sorry :)

**Comment by isaac-mercieca** [comment]
@kai It will be 3 in the morning. I will try to attend however as I belive
it is going to be interesting.

**Comment by TheRealAgentK** [comment]
My plan is to record it and make it available. But no guarantee :)

**Comment by TheRealAgentK** [comment]
https://zoom.us/j/8483994177

Starts in 28 mins from now.

**Comment by TheRealAgentK** [comment]
Recording of our meeting earlier this week:

https://www.youtube.com/watch?v=dge7qHXgE34&feature=youtu.be
