### ISSUE TITLE
Exclude WEB-INF folder

### ISSUE THREAD

**Issue by timbeadle** [cflint/CFLint#29]
I want to ignore the WEB-INF folder created by Railo under my wwwroot folder. Is this possible?

**Comment by ryaneberly** [comment]
Sure Tim,

It's similar to:
https://github.com/cflint/CFLint/wiki/Are-There-Any-Recipes-Out-There%3F

Change cflintexclude.json
to include:
<code>{"file":".\*WEB-INF.\*"}</code>

This is a regular expression that says to exclude any file with WEB-INF in it's path.

Note, each of the items is separated by a comma, a full example would be:

<code>
[
{"function":"init"},
{"file":".\*WEB-INF.\*"}
]</code>

**Comment by timbeadle** [comment]
@ryaneberly Thanks! That's very helpful :smile:
