### ISSUE TITLE
Allowing to ignore CFQUERYPARAM_REQ with SQL code

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#295]
This is coming out of the resolution of #282.

Issues of type 1,2,4 and 5 as shown there can now be successfully ignored by using 

```
 <!---
       @CFLintIgnore CFQUERYPARAM_REQ
  --->
```

in front of the query.

In a scenario such as below, we're now stuck between a rock and a hard place though:

```
        <cfquery name="commentsSelect" datasource="#arguments.siteDomain#com" cachedwithin="#createTimeSpan(0,0,5,0)#">
            SELECT
                M.firstName
            FROM #application.linkedServerName#.schema.dbo.Comment C WITH (NOLOCK)
            LEFT OUTER JOIN something SM WITH (NOLOCK)
                ON C.memberID = SM.memberID
            INNER JOIN somethingelse m
                ON m.memberID = sm.memberid
            LEFT OUTER JOIN #application.linkedServerName#.schema.dbo.Author A WITH (NOLOCK)
                ON C.aID = A.aID
            WHERE
                eID = #arguments.someNumber# AND
                moderated = 1
            ORDER BY
                cID
        </cfquery>
```

CFlint will report on three instances here:

1. FROM #...#.schema...
2. LEFT OUTER JOIN #...#.schema...
3. eID = #arguments.someNumber#

Number 3 is obviously something we'd want to fix and we can easily change the code. CFLint will then still report on 1/2 - which _might_ lead to SQL injection issues, but they're impossible to fix with CFQUERYPARAM on most (if not all) DB servers.

Currently the only way to get them out of the reporting is to apply

```
        <!---
        @CFLintIgnore CFQUERYPARAM_REQ
        --->
```

to the whole query. But unfortunately that will then leave the whole query open for potential _actual_ CFQUERYPARAM violations being introduced later. Those would never be reported because the query is fully ignored. Now imagine you have long and complex queries spreading over literally hundreds of lines and those post-ignore introduced violations would be really hard or impossible to spot when they're not reported.

The ideal solution would be to allow @CFLintIgnore inside of SQL code so that I could instead do:

```
        <cfquery name="commentsSelect" datasource="#arguments.siteDomain#com" cachedwithin="#createTimeSpan(0,0,5,0)#">
            SELECT
                M.firstName
           <!---
           @CFLintIgnore CFQUERYPARAM_REQ
            --->
            FROM #application.linkedServerName#.schema.dbo.Comment C WITH (NOLOCK)
            LEFT OUTER JOIN something SM WITH (NOLOCK)
                ON C.memberID = SM.memberID
            INNER JOIN somethingelse m
                ON m.memberID = sm.memberid
           <!---
           @CFLintIgnore CFQUERYPARAM_REQ
            --->
           LEFT OUTER JOIN #application.linkedServerName#.schema.dbo.Author A WITH (NOLOCK)
                ON C.aID = A.aID
            WHERE
                <!--- FIX THIS ISSUE --->
                eID = #arguments.someNumber# AND
                moderated = 1
            ORDER BY
                cID
        </cfquery>
```

I'm not sure if that's possible with the current parsing/ignoring model - I'm not even sure to which extent SQL gets treated as more as a string blurb at this stage. But it'd be great if we had a solution as outlined above :)

**Comment by ryaneberly** [comment]
It might be more viable to support

before the cfquery tag.

**Comment by ryaneberly** [comment]
Ok.  I implement a rudimentary parser inside the checker.  
 will work inside <cfquery/>.   It will ignore variables on the same line or the next line.

**Comment by TheRealAgentK** [comment]
will give that a try today with some realsies code :)

**Comment by isaac-mercieca** [comment]
Another suggestion could be to enhance the rule to also take into
consideration the scope i.e. if the variable being dumped is either in
application or session scopes then it would be impossible to perform SQL
injection, given that these values are never populated by client-side call
which was not validated properly.

**Comment by TheRealAgentK** [comment]
Yeah @ryaneberly suggested something similar, too - but I'm not a big fan of that and it doesn't solve the issue entirely either. 

a) you could still have something like 

```
application.injectMe = argument.pleasePutYourSQLCodeHere
...
<cfquery>
SELECT * FROM everything where b = #application.injectMe#
</cfquery>

```
That would be dumb, but hey - people do crazy things.

b) It wouldn't solve scenarios where people might not use "allowed" scopes, but for valid reasons can't cfqueryparam there, like example 4 in #282 .

**Comment by isaac-mercieca** [comment]
I see your point however by using the ignore functionality it still not
enforce the rule because people will end up using the ignore for no reason
at all and I personally do not like using ignore ... I do not know maybe
there is another way which was not taught of yet.

**Comment by TheRealAgentK** [comment]
@ryaneberly Testing your implementation of a rudimentary parser at the moment and it mainly works really well. I'll send you a few cases in which it doesn't via Slack DM in the CFLint Slack.

**Comment by TheRealAgentK** [comment]
Tested again a production code base too and seems to working all fine now! Thx @ryaneberly !
