### ISSUE TITLE
Findbugs: totalsize should be lines of code scanned

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#303]
Currently CFLintStats calculates totalsize as the sum of the length of the files scanned. 

I dug around a bit in what Findbugs for Java does and it's the sum of lines of code over there. Can we adjust that in CFLintStats, @ryaneberly ?

**Comment by ryaneberly** [comment]
Good catch.  It should be fixed now.

**Comment by TheRealAgentK** [comment]
Adjusted the HTML report output LOC, closing ticket.
