### ISSUE TITLE
Discussion: Is the Wiki a good idea?

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#306]
I find that the CFLint Wiki has quite a few pages that are probably not being updated as they should and have become stale or outdated in parts.

I wonder if at least parts of the information kept in the Wiki should instead be in Readme.md or Changelog.md or Manual.md files and be tracked with the repository instead as Wiki pages. At least it's easy(ier) then to track changes across releases.

**Comment by KamasamaK** [comment]
I think a changelog is a nice addition. The README probably shouldn't be too extensive. It should cover the essentials in good detail, but most everything else could just be mentioned or covered at a basic level with links (to wiki pages/a manual/documentation website) that go into more details with examples. For instance, I think brief descriptions of each built-in rule and if applicable their parameters would be very useful, but unnecessary in a README.

**Comment by TheRealAgentK** [comment]
@KamasamaK The new readme in the dev branch will essentially be

- General info
- quick start
- user manual
- external resources/other projects.

There's a changelog.md and I've also added a rules.md where the rules can be documented.

In a nutshell, I want to get rid of the Wiki. It tends to be out-of-date with stale info that doesn't make sense for version x.y all of a sudden etc.

With documentation in the repo, versioned with code and releases, that's much better to manage.

**Comment by KamasamaK** [comment]
I see you already have a `RULES.md` to handle that concern. I will have to see how it all looks when it's more filled out. I just prefer more modularity.

**Comment by TheRealAgentK** [comment]
Closing as we've moved most over and the wiki is pretty much deprecated now (but one or two pagesI need to have a look at)
