### ISSUE TITLE
Test Harry's Sublime/CFLint instructions and i18n to English if ok

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#307]
https://github.com/cflint/CFLint/wiki/Installation-von-CFLint-&-Sublime-Linter-Plugin

**Comment by KamasamaK** [comment]
When translated, it became clear that the instructions were for an older version of CFLint. I have updated the instructions to work with the current version of both CFLint and the SublimeLinter plugin. I have started to update the plugin to work with the JAR file, and will update the instructions accordingly when finished.

**Comment by TheRealAgentK** [comment]
@KamasamaK Awesome - a couple of people in the cflint channel on the CFML Slack team have started to look into that, too. Not sure if you're on there, but it might be worth coordinating with them.

**Comment by KamasamaK** [comment]
My changes have already been merged to [SublimeLinter-contrib-CFLint](https://github.com/ckaznocha/SublimeLinter-contrib-CFLint) including documentation updates. Once the maintainer creates a new release, the wiki page will be outdated and largely unnecessary, but I will revisit at that time. Either way, I think this issue can be closed.

**Comment by TheRealAgentK** [comment]
@KamasamaK Awesome, thanks. @derrick13 - would you mind having a look at the updated repo @KamasamaK mentioned and confirm that which those instructions and their codebase the setup works?

**Comment by derrick13** [comment]
@agentk Unfortunately after Sublime updated my CFLint SublimeLinter plugin it stopped working. The configfile is not found, even if I define "aux_config_dirs".
It would be great if someone could share a working example (on windows).
I would enable these rules only: "MISSING_VAR,OUTPUT_ATTR,AVOID_USING_STRUCTNEW,AVOID_USING_ARRAYNEW,UNUSED_LOCAL_VARIABLE"

This is my configuration atm (after several tries):
```
               "cflint": {
                "@disable": false,
                "args": [],
                "aux_config_dirs": [
                    "D:/projekte_cf/contens/contens5",
                    "D:/projekte_cf/contens/contens5/",
                    "D:/projekte_cf/contens/contens5/contens",
                    "D:/projekte_cf/contens/contens5/contens/"
                ],
                "config_file_name": "cflintrc.xml",
                "excludes": [],
                "jar_file": "D:/CFLint/CFLint-1.1.0-all.jar"
            },
```

And this is my minimal configuration file "cflintrc.xml":
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<config>
    <rule name="MISSING_VAR"></rule>
</config>
```

**Comment by TheRealAgentK** [comment]
@KamasamaK Help? :-)

**Comment by KamasamaK** [comment]
I've confirmed with @derrick13 on Slack that it's not the case that "The configfile is not found". The config file was loaded, but not working as he expected. We could only get the `<excludes code="RULE_CODE" />` tags to work. This is beyond the scope of the plugin. He has also been informed that the XML format being used is being deprecated.

**Comment by TheRealAgentK** [comment]
Not sure where to go from here @ryaneberly

**Comment by TheRealAgentK** [comment]
I close this as we seem to have a working Sublime integration again now.
