### ISSUE TITLE
EXCESSIVE_ARGUMENTS is not configured correctly

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#308]
Now that the CFLint integration into cfeclipse works nicely, I get message:

![grafik](https://user-images.githubusercontent.com/802702/27544307-09a7e57a-5a8d-11e7-99f9-65d4990c6f6e.png)

**Comment by ryaneberly** [comment]
@denuno ,  I don't know.  is this a back version of CFLint?

**Comment by bardware** [comment]
> a back version of CFLint

`org.cfeclipse.cflint_1.1.0.201707040628.jar` seems to have fixed it. Thanks!
