### ISSUE TITLE
Trying out the configfile from the command line and getting errors

### ISSUE THREAD

**Issue by jerronjames** [cflint/CFLint#31]
Trying out the configfile from the command line and getting errors. Maybe I'm using it wrong though. Posting in case it's a bug or we just need some documentation on it.

java -jar CFLint-0.3.0-all.jar -folder=cfc -configfile=cflint

Exception in thread "main" java.lang.ClassCastException: com.cflint.config.CFLintPluginInfo cannot be cast to com.cflint.config.CFLintConfig
 	at com.cflint.main.CFLintMain.execute(CFLintMain.java:222)
        at com.cflint.main.CFLintMain.main(CFLintMain.java:164)

inside cflint file:
&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
&lt;CFLint-Plugin&gt;
	&lt;ruleImpl name=&quot;CFDumpChecker&quot;&gt;
		&lt;message code=&quot;code&quot;&gt; 
			&lt;messageText&gt;messageText&lt;/messageText&gt;
			&lt;severity&gt;WARNING&lt;/severity&gt;
		&lt;/message&gt;
	&lt;/ruleImpl&gt;
&lt;/CFLint-Plugin&gt;

**Comment by ryaneberly** [comment]
The config format is slightly differently than the CFLintPluginInfo.

I imagine there was a reason, I just can't recall it :p.  Oops.

&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
&lt;config&gt;
    &lt;rules name=&quot;CFDumpChecker&quot;&gt;
        &lt;message code=&quot;code&quot;&gt;
            &lt;messageText&gt;messageText&lt;/messageText&gt;
            &lt;severity&gt;WARNING&lt;/severity&gt;
        &lt;/message&gt;
    &lt;/rules&gt;
&lt;/config&gt;

**Comment by ryaneberly** [comment]
And it should be <rule/> not <rules/>

I pushed that change to master.

&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
&lt;config&gt;
    &lt;rule name=&quot;CFDumpChecker&quot;&gt;
        &lt;message code=&quot;code&quot;&gt;
            &lt;messageText&gt;messageText&lt;/messageText&gt;
            &lt;severity&gt;WARNING&lt;/severity&gt;
        &lt;/message&gt;
    &lt;/rule&gt;
&lt;/config&gt;

**Comment by jerronjames** [comment]
Beautiful. I just tested it. Thanks Ryan, I was looking at it last night and couldn't figure it out.
