### ISSUE TITLE
CommandBox integration

### ISSUE THREAD

**Issue by ryaneberly** [cflint/CFLint#310]
Install the jar.  Run it, make it available on ForgeBox etc.

**Comment by lramirez925** [comment]
Commandbox now supports simple jar downloads from maven. Maybe this is now easier to do? Just hosting a jar on forge box seems to be a bit overkill. 

Would there be interest in a module for this?

**Comment by ryaneberly** [comment]
Yes.  Either pull from maven or pull from github releases, either would
work.

**Comment by TheRealAgentK** [comment]
I've got a Forgebox integration with another library I've done and I hooked that up to github. It hooks into git tags, so you don't even have to have only official releases but you can grab branches/tags from Forgebox then.

**Comment by TheRealAgentK** [comment]
Hey @denuno - you're still keen to look into this for 1.3?

**Comment by ryaneberly** [comment]
Per #560 this is done.
