### ISSUE TITLE
Document IDE integrations

### ISSUE THREAD

**Issue by ryaneberly** [cflint/CFLint#312]
CFEclipse.   etc.

**Comment by KamasamaK** [comment]
How much of the documentation should be done in this project as opposed to the IDE plugin's? I think a link to the plugin's project would be sufficient in most cases, as is being done now, and try to improve their documentation. Most (all?) of the ones I've seen have a GitHub repo.

**Comment by TheRealAgentK** [comment]
That is a very good point. Maybe we just want to provide a list of github repos and let other people deal with it?

**Comment by ryaneberly** [comment]
Mm.  I agree.   A list of integrations and HOW they integrate (i.e, they use the command line and consume the JSON output, etc)  , so we can avoid breaking them downstream.
