### ISSUE TITLE
Investigate and document rule inclusion/exclusion process and precedences

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#314]
.cflintrc vs Annotations for instance.

**Comment by TheRealAgentK** [comment]
@ryaneberly @KamasamaK Do you guys think we have done that extensively enough in the current README? At least for now?

**Comment by KamasamaK** [comment]
I have by no means thoroughly tested all of the scenarios, so I would have to really see how it works first. I do feel that the documentation could provide a better explanation for the rule definitions. Especially how to use `parameter` to customize existing rules (if that can be done currently).

I'm still unclear about the inclusion process for `.cflintrc` (e.g. using `includes`). I just made the schema match the Java class, so it has `code`, `severity`, and `messageText`. The `code` seems to work, but I am unable to see the `severity` and `messageText` have any impact. I only noticed them have an impact when changed under `rules`. Is this known/intended? I should update the schema description if these are supposed to be ignored as they are with `excludes`.

**Comment by KamasamaK** [comment]
Regarding customizing the parameter, I tried this to change EXCESSIVE_FUNCTIONS:
```
{
  "rule": [
    {
      "name": "TooManyFunctionsChecker",
      "className": "TooManyFunctionsChecker",
      "message": [
        {
          "messageText": "Component ${filename} has too many functions. Should be fewer than ${maximum}.",
          "code": "EXCESSIVE_FUNCTIONS",
          "severity": "WARNING"
        }
      ],
      "parameter": [
        {
          "name": "maximum",
          "value": "20"
        }
      ]
    }
  ],
  "excludes": [],
  "includes": [],
  "inheritParent": false
}
```

It successfully changed the message to use the new parameter value, but the rule does not actually change to make 20 the maximum. Again, I don't know if this is intended. I will test more to see how the cascading works and what is required. The "VariableNameChecker" seems especially interesting since it has multiple `message`s and `parameter`s.

**Comment by TheRealAgentK** [comment]
Next step: @KamasamaK to add a few testcases

**Comment by ryaneberly** [comment]
@KamasamaK ,  This is implemented now.
1. Overriding the rule in the .cflintrc will honor the parameters as well as the messages now.  Note: the _entire_ rule definition must be copied, there is no inheritance.

2.  You can specify specific parameters in the parameters section of the .cflintrc file.
```
{
  "inheritParent" : true,
  "parameters" : 
      {"TooManyFunctionsChecker.maximum" : "33"}
}
```

**Comment by TheRealAgentK** [comment]
I think we still need to add the outcome of this ticket to the documentation.

**Comment by ryaneberly** [comment]
Agreed.  Though @KamasamaK did an excellent update to the README.MD to reflect this.   And #505 would cover the nitty gritty of each specific rule and parameter option.

**Comment by TheRealAgentK** [comment]
Oh, sorry - if readme has been updated, then it's all good.

**Comment by ryaneberly** [comment]
np.  Thanks for keeping us honest
