### ISSUE TITLE
inheritPlugins in .cflintrc should be always true 

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#315]
... and removed from cflintrc as a settings option.

Discussed with @ryaneberly and we couldn't think of any use case in which you'd need inheritPlugins = false --- because it can essentially be achieved through excluding rules.

**Comment by TheRealAgentK** [comment]
I realised that if I fully refactor inheritPlugins out, it'll break everyones CFLint setup because the config parser will stumble over inheitPlugins being there and then not being able to map it to a field. 

I suggest for 1.2.0. we just make sure that if someone overwrites inheritPlugins from true to false, we ignore that and always treat it as true and then remove the setting in the 1.3.0.

**Comment by ryaneberly** [comment]
Add a warning message on the console?   "inheritPlugins is deprecated and
will me removed in the future"

**Comment by TheRealAgentK** [comment]
@ryaneberly Done
