### ISSUE TITLE
Document CFLint contribution/build/test/play with process

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#317]
Stuff like:

import project into Eclipse / IntelliJ
how to run a test
how to build maven artefacts
how to execute from IDE and step into code etc

**Comment by cybersonic** [comment]
+1 for this! I am not a maven person but could easily get into the code, I have spent an hour getting this project and then cfparser and it seems like I am going down a rabbit hole. It would be great to know how I can build it, so I can then at least do a bunch of typo fixes (spotted loads) and test my new rules.

**Comment by ryaneberly** [comment]
Hi @cybersonic.  Thanks for your interest in making CFLint better.

How does this look:
https://github.com/cflint/CFLint/blob/dev/BUILDING.md

**Comment by ryaneberly** [comment]
You do not want to start with trying to build cfparser from scratch, it is quite the 'rabbit hole'.  The gradle build of CFLint will take care of the dependencies for you.

The maven build is deprecated and it only hanging on until we get the release process migrated to gradle.  Your experimenting with CFLint is better spent with gradle.

**Comment by cybersonic** [comment]
Thanks for that! I shall have a look now!
