### ISSUE TITLE
JSON output questions (int/string and locations array)

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#318]
Please document the different output schemas (e.g. JSON, XML, text)

**Comment by KamasamaK** [comment]
As I am using JSON currently, I wanted to point out that numbers such as `locations[i].column` and `locations[i].line` are being output as strings instead.

**Comment by TheRealAgentK** [comment]
@ryaneberly --- do you know of anything downstream (like IDE tools, build server plugins etc) that would break if we fixed JSON datatypes?

**Comment by TheRealAgentK** [comment]
@KamasamaK 

In the dev branch (and from the next official release on), the Findbugs XML output style is actually compliant with the findbugs xml schema definition.

I guess you could probably quite easily come up with an xml schema for CFLint's "default"/internal XML - keen to tackle that @KamasamaK ?

I personally haven't used the JSON/text output, but should should be reasonably straight forward to document. You could start by documenting the current output (please use the dev branch) formats in the Wiki.

**Comment by ryaneberly** [comment]
@TheRealAgentK,  I'm not aware of any issues with 'fixing' the number output in JSON with downstream tooling.  But I'm not familiar with many of the downstream usages.

**Comment by TheRealAgentK** [comment]
@ryaneberly @KamasamaK I guess the question is then - do we want/need to have numeric values like the counts, line, column etc. as numeric data in JSON or are we ok with just leaving them as strings.

I'm not leaning very strongly either way here - what do other people think?

**Comment by KamasamaK** [comment]
I think the goal should be to use the proper data types. Breaking compatibility is a potential concern, but it should be easy enough to work around if it's an issue. The only ones I've really looked into are Atom's linter-cflint plugin, which uses the XML output, and SublimeLinter's which uses the text output. The other projects I've seen just appear to be using the Java directly.

Actually, the reason this came up is that I was seeing if I could change Atom's linter-cflint to use JSON instead of XML output. I was successful, but I had to use `parseInt()` on the values which shouldn't be necessary. Note that if JavaScript/ECMAScript's `parseInt()` is being used in any code currently it won't cause issues as it works fine even if it's already numeric.

**Comment by ryaneberly** [comment]
I don't feel strongly either.  I'm good with @KamasamaK
<https://github.com/kamasamak> 's recommendation.

**Comment by TheRealAgentK** [comment]
@KamasamaK @ryaneberly I'll implement the String->Int changes in dev later, re @KamasamaK's second question (locations array). I honestly don't know at this stage - I looked into the whole JSON output mechanism for the first time yesterday :)

**Comment by TheRealAgentK** [comment]
Schema documentation moved into #322, @KamasamaK .

**Comment by TheRealAgentK** [comment]
Done, schemas and use of locations element is being dealt with in #322

**Comment by ryaneberly** [comment]
We just need to change
jg.writeStringField()  to jg.writeNumberField() in order to make the
numbers come out.

Changing the locations not be an array may break downstream tooling.
 There is an opportunity to more concisely represent issues that repeat
within in a file by just repeating the line and column numbers in the
locations array -- is that useful or confusing?

**Comment by KamasamaK** [comment]
For any tool using the JSON output, I can't think of a way it _wouldn't_ break removing the array. 

I understand what you're proposing, which would be for both JSON and XML, but I have a feeling that could also break tooling due to assumptions people made about the output, which is precisely why I felt documenting output schemas was necessary. For example, Atom's `linter-cflint` package assumes a single location for each issue.

**Comment by ryaneberly** [comment]
Good point.  Something to visit at 2.0?

**Comment by TheRealAgentK** [comment]
"jg.writeStringField()  to jg.writeNumberField() in order to make the
numbers come out." --- that's already been done in fe73779a35fc0b7c9490bd2f1defb9635f30b766

**Comment by TheRealAgentK** [comment]
"There is an opportunity to more concisely represent issues that repeat
within in a file by just repeating the line and column numbers in the
locations array -- is that useful or confusing?....    In fact after looking at it a bit more, it should already be doing that."

I don't think it is dong that at this stage. I can't see it in my daily usage at least.

But you're making a very good point @ryaneberly --- we could have a grouping by file mechanism that lists issues differently and with multiple location elements per issue.

Nothing to look deeper at now, I'd agree - I'd leave locations unchanged for 1.x and we'll have a rethink for 2.0.
