### ISSUE TITLE
no cflint version could be extracted with SublimeLinter

### ISSUE THREAD

**Issue by piousteph** [cflint/CFLint#33]
Hi,
I'm trying to use cflint with SublimeText and SublimeLinter. It's working fine with version 0.2 but with 0.4 i have this message :

![image](https://cloud.githubusercontent.com/assets/11159637/6328331/97f915e2-bb66-11e4-9019-e8e424bc9751.png)

could you please if it's possible to remove this extra CR
Thanks
Regards
Stephane

**Comment by piousteph** [comment]
Hi,
I have found the issue, the cflint version is x.y but SublimeLinter search for x.y.z
I have updated the file pom.properties file and replace
version=0.4 by version=0.4.0
Could you please update the source
Thanks
Regards
Stephane

**Comment by ryaneberly** [comment]
I changed 0.4 to 0.4.0. 
thanks Stephane
