### ISSUE TITLE
Failed to execute goal on project CFLint: Could not resolve dependencies

### ISSUE THREAD

**Issue by jimpriest** [cflint/CFLint#34]
Trying to install on Windows...

I've downloaded Maven and have it in C:\maven\bin

I ran the mvn clean install and it downloads a bunch of things from maven.apache.org (or correctly dumps them in my .m2 directory it appears) but then it bombs with:

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 28.764 s
[INFO] Finished at: 2015-03-02T08:04:31-05:00
[INFO] Final Memory: 11M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project CFLint: Could not resolve dependencies
 for project com.cflint:CFLint:jar:0.1.9: Failed to collect dependencies at com.
cfparser:cfml.parsing:jar:1.0.0: Failed to read artifact descriptor for com.cfpa
rser:cfml.parsing:jar:1.0.0: Could not find artifact com.cfparser:cfparser:pom:1
.0.0 in cfparser (https://raw.github.com/cfparser/cfparser/mvn-repo/) -> [Help 1
]

And this doesn't seem to exist:
https://raw.github.com/cfparser/cfparser/mvn-repo/

Am I doing something stupid or has something moved?  :)

Thanks!
Jim

**Comment by jjames967** [comment]
What are you actually building that requires CFLint:jar:0.1.9? 0.4 is the current release.

**Comment by jimpriest** [comment]
Like I said - am I doing something stupid :)   

Had a bit more time this AM and actually RTFM and noticed the link to the JAR file.  Might be worth adding a note on the "How do I install this tool" page that you don't need to build it from source - a pre-compiled JAR is available to download....

Thanks!

**Comment by ryaneberly** [comment]
Hi jimpriest,

I added https://github.com/cflint/CFLint/wiki/Quick-Start
thanks for the input
