### ISSUE TITLE
GLOBAL_LITERAL_VALUE_USED_TOO_OFTEN triggered on CF_SQL_

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#340]
I have script components with `addParam()` for parameterizing queries, and the setting `cfsqltype` within it to the enumerated values like "CF_SQL_INTEGER" and "CF_SQL_VARCHAR" is triggering `GLOBAL_LITERAL_VALUE_USED_TOO_OFTEN`. Does it make sense to make variables for those values or should it ignore them?

**Comment by ryaneberly** [comment]
Good point.  That should be changed. 


`
spService.addParam(cfsqltype="cf_sql_varchar", type="in",value=form.title); `

**Comment by ryaneberly** [comment]
Added a harded exclusion to LiteralChecker for any literal starting with cf_sql_
