### ISSUE TITLE
GLOBAL_LITERAL_VALUE_USED_TOO_OFTEN triggered by built in function arguments

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#344]
When running analysis on the following code:

```
component {
    function foo() {
        arraySort(bar, "numeric", 'ASC');
        arraySort(bar, "numeric", 'ASC');
        arraySort(bar, "numeric", 'ASC');
        arraySort(bar, "numeric", 'ASC');
        arraySort(bar, "numeric", 'ASC');
        arraySort(bar, "numeric", 'ASC');
    }
}
```

the resulting XML file will contain several issues of:

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<issues version="1.2.0-SNAPSHOT" timestamp="1499851638">
  <issue severity="WARNING" id="GLOBAL_LITERAL_VALUE_USED_TOO_OFTEN" message="GLOBAL_LITERAL_VALUE_USED_TOO_OFTEN" category="CFLint" abbrev="GL">
    <location file="C:\Inbox\cflint-test\TestAsc.cfc" fileName="TestAsc.cfc" function="foo" column="25" line="6" message="Literal numeric occurs several times in one or more files. Consider giving it a name and not hard coding values." variable="numeric">
      <Expression><![CDATA['numeric']]></Expression>
    </location>
  </issue>
  <issue severity="WARNING" id="GLOBAL_LITERAL_VALUE_USED_TOO_OFTEN" message="GLOBAL_LITERAL_VALUE_USED_TOO_OFTEN" category="CFLint" abbrev="GL">
    <location file="C:\Inbox\cflint-test\TestAsc.cfc" fileName="TestAsc.cfc" function="foo" column="36" line="6" message="Literal ASC occurs several times in one or more files. Consider giving it a name and not hard coding values." variable="ASC">
      <Expression><![CDATA['ASC']]></Expression>
    </location>
  </issue>
</issues>
```

It's reacting to the strings `numeric` and `ASC`, which are built-in function parameters.

Solving this will probably be tricky, because the rule would have to become more intelligent -- know which parameters of which functions to ignore. Some of the built in functions take strings as parameters, which _should_ be considered, while others take strings as (sort-of) enums, defined by the ColdFusion API, and these should be excluded from analysis.

**Comment by ryaneberly** [comment]
For now I took a shortcut by allowing ignoring special 'words' like DESC,ASC,NUMERIC,TEXT etc.
Detecting the _position_ and _builtin function name_ is tricky within the plugins.

**Comment by mpaluchowski** [comment]
Can we add the following exceptions?

* `string`, and other type parameters used in `javaCast`
* `all` and other parameters used in `ReReplace`
* punctuation literals, such as `.`, `,`, `;`, `:`, `_`, `-`
* empty string (yes, `""` and `''` seem to trigger the rule too)

**Comment by ryaneberly** [comment]
yes.  that helps round out the list.  Thank you!

**Comment by ryaneberly** [comment]
REReplace: one,all
JavaCast: bigdecimal boolean byte char int long float double short string
null
