### ISSUE TITLE
PARSE_ERROR on scoped variable assignment in CFM

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#346]
Scanning this code:

```
<cfset someScope.condition = NOT someScope.productIndex MOD 2 EQ 0>
```

produces a `PARSE_ERROR` with a console output of `line 1:49 mismatched input 'MOD' expecting <EOF>`. The error disappears when the variable scope is removed, so this one scans fine:

```
<cfset condition = NOT productIndex MOD 2 EQ 0>
```

**Comment by KamasamaK** [comment]
I've confirmed this. I'd also like to note that it's no different when replacing `NOT` with its symbolic alternative:
```
<cfset someScope.condition = ! someScope.productIndex MOD 2 EQ 0>
```

It is fine, however, when adding parentheses:
```
<cfset someScope.condition = NOT (someScope.productIndex MOD 2 EQ 0)>
```

Given the order of operator precedence, that is an equivalent statement.

**Comment by ryaneberly** [comment]
Related to 
https://github.com/cfparser/cfparser/issues/84

**Comment by ryaneberly** [comment]
parsing is fixed.
