### ISSUE TITLE
PARSE_ERROR on component with a name coinciding with one instantiated elsewhere

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#347]
Here's an odd one. Place the following two components in the **same directory**:

```
// Tag.cfc
component {
	public any function foo() {
		var bar = createObject('component', 'somepackage.User');
	}
}
```

```
// User.cfc
component {
}
```

Note:

* `User.cfc` can have any content or not, it's empty in this case.
* `User.cfc` is _not_ under `somepackage` but in the same directory as `Tag.cfc`. The error occurs also when there _exists_ a component `somepackage.User`, in addition to the `User` here.

Running CFLint on a folder with these two files will report a `PARSE_ERROR` on `User.cfc`:

```xml
<issue severity="ERROR" id="PARSE_ERROR" message="PARSE_ERROR" category="CFLint" abbrev="PE">
  <location file="C:\Inbox\cflint-test\User.cfc" fileName="User.cfc" function="" column="0" line="1" message="Unable to parse" variable="">
    <Expression><![CDATA[]]></Expression>
  </location>
</issue>
```

**Comment by ryaneberly** [comment]
@mpaluchowski,  I can't reproduce this using the same files you mentioned and the code the from dev branch.
Tag.cfc
User.cfc
and somepackage/User.cfc

**Comment by mpaluchowski** [comment]
True. Seems it _doesn't_ occur when the referenced file is in place, even when there's one with the same filename. So, here's a recap:

This situation **triggers** the error:

```
Tag.cfc
User.cfc
```

These **don't trigger** the error:

```
Tag.cfc
SomethingElse.cfc
```

```
Tag.cfc
User.cfc
somepackage/User.cfc
```

**Comment by mpaluchowski** [comment]
I one of our code bases I have 3,000 instances of this happening, so this one would be a blocker for use to use with our code. I'm not sure if conditions are identical (it's tricky and time consuming to test), so I'll wait for a fix for this one and see if that fixes also these issues. Otherwise, this could also occur in different circumstances.

**Comment by ryaneberly** [comment]
@mpaluchowski , Thanks for helping isolate that one.  It was caused by a plugin error.  It is fixed.
