### ISSUE TITLE
Remove and deprecate "output" on top-level of .cflintrc

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#356]
Similar to what we did for inheritPlugins

deprecate in 1.2.0
remove in 1.3.0

**Comment by ryaneberly** [comment]
We can safely remove the field anytime if we use

`@JsonIgnoreProperties(ignoreUnknown = true)`

**Comment by TheRealAgentK** [comment]
So - do we want to remove output and inheritPlugins now for 1.2.0 then and go back to #315?

Regardless, I've just added a message for output to becoming deprecated in 1.3.0

**Comment by TheRealAgentK** [comment]
Actually, it seems that output is NEVER used anywhere in code beyong CFLintConfig :)
