### ISSUE TITLE
Maven build fails using the ZIP file from GitHub since it needs the `.git` folder

### ISSUE THREAD

**Issue by ryaneberly** [cflint/CFLint#363]

**Comment by denuno** [comment]
Ha!  Well, there goes the idea of using the git hash as a version number.  Hadn't even thought about that, but one probably shouldn't require git just to build.

**Comment by ryaneberly** [comment]
@denuno I think it remains a fine basic implementation.  People doing releases will typically have a git clone.   ... as long as we can get the build to _not fail_ when using the zip repo.

**Comment by denuno** [comment]
Indeed!  This fixed that build fail at least.  It's just funny how ubiquitous source control is in my mind now.

**Comment by ryaneberly** [comment]
@denuno . Thanks!
