### ISSUE TITLE
PARSE_ERROR when "function" used as variable name

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#364]
The word `function`, used as a variable name, triggers a `PARSE_ERROR`. It's not [among the list of reserved words](https://helpx.adobe.com/coldfusion/cfml-reference/reserved-words-and-variables/reserved-words.html) and the code works fine. There _could_ be a new rule advising to avoid using reserved words for other purposes than their intended ones, but it shouldn't be causing parsing errors.

Here are some test cases:

```
public function init(required any function, required any foo) {}
```

```
<cfloop array="#function.subcategories#" index="subCategory">
  <li>#subCategory.description#</li>
</cfloop>
```

**Comment by TheRealAgentK** [comment]
I feel this is a cfparser issue.

**Comment by ryaneberly** [comment]
Yes it is.

**Comment by denuno** [comment]
I've got a fix for it, BTW.

**Comment by ryaneberly** [comment]
This will be in 1.3.0 which will use the next version of cfparser
https://github.com/cfparser/cfparser/issues/83
