### ISSUE TITLE
ANTLR Tool version 4.6 mismatch

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#366]
Running the JAR returns a warning:

```shell
ANTLR Tool version 4.6 used for code generation does not match the current runtime version 4.7
```

This seems to come from cfparser. The ANTLR dependencies in cfparser and in CFLint all look correct and pointing to ANTLR 4.7 When I build both of them locally, with Maven, the warning _doesn't_ appear. It only does appear when I use the cfparser release from the global Maven repository.

Perhaps the computer, where cfparser is buitlt for releases, has ANTLR 4.6 installed in a local classpath, that's overriding the one in Maven's POM? Here's [ANTLR's Getting Started guide](https://github.com/antlr/antlr4/blob/master/doc/getting-started.md) showing how this could be installed.

**Comment by TheRealAgentK** [comment]
I just tried that and can confirm @mpaluchowski's observation. When building cfparser locally and using that I don't see the warning either.

**Comment by ryaneberly** [comment]
Me too.  I deployed cfparser 1.4.10 which has the antlr 4.7 upgrade in it.
  CFLint 1.2.0 will use that.

**Comment by ryaneberly** [comment]
pom updated to use cfparser 2.4.10
