### ISSUE TITLE
EXCESSIVE_FUNCTIONS uses absolute path in message

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#367]
The `location`.`message` for EXCESSIVE_FUNCTIONS includes the absolute path to the file. I feel this is unnecessary in the message and is already included in the `file` attribute. It is also inconsistent with other rules such as COMPONENT_HINT_MISSING which only uses the component name.

**Comment by TheRealAgentK** [comment]
Will have a quick look.

**Comment by KamasamaK** [comment]
Also, to be more grammatically correct, it should be "*fewer* than 10".

**Comment by KamasamaK** [comment]
Another issue I found for the same rule: in script components it will report multiple times. It seems to scale with the number of functions and is approximately reported the number of functions over `maximum` (e.g. there will be about 17 reports for a component with 27 functions and a `maximum` of 10). Tag components don't seem to be affected.

**Comment by ryaneberly** [comment]
EXCESSIVE_FUNCTIONS now uses component name, and only reports once.  grammar fix also applied
