### ISSUE TITLE
Remove inheritPlugins and output

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#368]
#315 #333 #356 

Get fully rid of in 1.3.0.

**Comment by KamasamaK** [comment]
Is this finished or should it be pushed to 1.4.0?

**Comment by ryaneberly** [comment]
Looks like the code is still active.  Moving to 1.4.0

**Comment by TheRealAgentK** [comment]
Yes, should be pushed to 1.4.0, sorry. Jeez, you guys are breezing through tickets and issues over the last week. I'll try to spend a bit of time tomorrow and on the weekend to at least go through all the recent changes :)

**Comment by KamasamaK** [comment]
@cybersonic It doesn't look like you are using CFLint 1.3.0 based on that message. Can you please confirm if you get this message from v1.3.0?

**Comment by cybersonic** [comment]
I don’t get it from 1.3.  I thought I was using the latest on that machine. Alas no. 

Mark Drew
