### ISSUE TITLE
CFLint-ui asking for 4G of Memory

### ISSUE THREAD

**Issue by jjames967** [cflint/CFLint#38]
Using a computer with a smaller amount RAM, I'm getting an error:

"Invalid maximum heap size: -Xmx4g
The specified size exceeds the maximum representable size."

This is generated in the cflint-ui.bat file. I think it may be wise to let the system and Java negotiate RAM space. Perhaps even starting the heap size at 512M of memory of memory. Perhaps even smaller.

**Comment by jjames967** [comment]
I'm using Windows 8.1 with 8G RAM. Only 2.5G RAM in use, but throwing that error.

**Comment by jjames967** [comment]
It still showed the error with 1G RAM allocation request.

**Comment by ryaneberly** [comment]
I'm backing change that out.  I put that in the app assembler when I was
attempting to deal with the parser hanging on me.  Memory was not the
problem, ambiguities were.
