### ISSUE TITLE
CFQUERYPARAM_REQ false positive with mixed case CFqueryparam

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#380]
a false positive is triggered when the case of the <cfquery> and <cfqueryparam> tags don't match, which is only stylistically messy but still valid

> 
> `<cfset user_id=1>`
> `<CFquery name="users" datasource="dsn">`
> 	SELECT 	user
> 	FROM 	users
> 	where 	user_id = `<CFqueryparam value="#user_id#" cfsqltype="CF_SQL_NUMERIC">`
> `</CFquery>`
> 
> 

with the latest dev branch

>  java -jar .\CFLint-1.2.0-all.jar -folder . -stdout -text
> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
> Issue
> Severity:WARNING
> Message code:CFQUERYPARAM_REQ
>         File: queryparam_req.cfm
>         Column:0
>         Line:5
>                 Message:`<cfquery>` should use `<cfqueryparam/>` for variable 'user_id'.
>                 Variable:'user_id' in function:
>                 Expression:`<CFquery name="users" datasource="dsn">`
>         SELECT  user
>         FROM    users
>         where   user_id = `<CFqueryparam value="#user_id#" cfsqltype="CF_SQL_NUMERIC">`
> `</CFquery>`
> 
> 
> Total files:1
> Total lines:7
> 
> Issue counts:1
> CFQUERYPARAM_REQ:1
> 
> Total issues:1
> Total warnings:1
> 

[queryparam_req.cfm.txt](https://github.com/cflint/CFLint/files/1184981/queryparam_req.cfm.txt)

**Comment by ryaneberly** [comment]
@zspitzer , the query param checker is case insensitive now.  Thanks!

**Comment by zspitzer** [comment]
confirmed it's working
