### ISSUE TITLE
Clarify/update documentation for command line use in Powershell

### ISSUE THREAD

**Issue by Ilaeria** [cflint/CFLint#400]
When running cflint over my local codebase via Powershell command line I was seeing different results to the output on our buildserver. After some troubleshooting with @TheRealAgentK we determined this was due to how Powershell parses multiple arguments. It would be useful if the documentation reflected that when running in Powershell, multiple arguments require double quotes, e.g.: 
java -jar CFLint-1.2.0-all.jar -includeRule "MISSING_VAR,QUERYPARAM_REQ,CFQUERYPARAM_REQ,AVOID_EMPTY_FILES"

I'm going to go ahead and write something up and do a PR for this quick fix today.

**Comment by TheRealAgentK** [comment]
Closed with PR #401, thx!
