### ISSUE TITLE
Named process for windows

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#407]
When running via the command line on windows, the process shows up as **Java(TM) Platform SE binary**

![image](https://user-images.githubusercontent.com/426404/29000073-bc450470-7aa3-11e7-8e74-6f08bbeb3bd7.png)

Launch4j lets you create a Cross-platform Java executable wrapper, so the CFLint process could show up as CFLint http://launch4j.sourceforge.net/index.html

**Comment by TheRealAgentK** [comment]
What'd be the ~ amount of bloat this wrapper would add? Ever used it @zspitzer ?

**Comment by zspitzer** [comment]
I've never tried, I only just googled it up after seeing the task manager naming

**Comment by TheRealAgentK** [comment]
We've decided to not do this, @zspitzer, sorry :-/
