### ISSUE TITLE
False positive unused var when local variable is used in queryparam

### ISSUE THREAD

**Issue by justinmclean** [cflint/CFLint#416]
local varied variables used in query params inside a cfquery tag are incorrectly marked as unused.

**Comment by justinmclean** [comment]
Example code
<cfcomponent>
<cffunction name=\"changePassword\">
<cfscript>
var salt = createUUID();
var hash = hash(password & salt);
var update = "";
</cfscript>
<cfquery name="update">
update logins
set hash = <cfqueryparam value="#hash#" cfsqltype="CF_SQL_VARCHAR">
</cfquery>
</cffunction>
</cfcomponent>

**Comment by TheRealAgentK** [comment]
Quick note: @ryaneberly and I set the testcase to @Ignore today so that we could deploy 1.2.3

**Comment by ryaneberly** [comment]
fixed and the test reenabled.
