### ISSUE TITLE
query param false positive for expressions with no variable use

### ISSUE THREAD

**Issue by justinmclean** [cflint/CFLint#417]
Example code

```
<cfquery name="queryName" datasource="#datasourceName#">
update users
set updated = "#createODBCDateTime(now())#"
</cfquery>
```

Note there no (reasonable) way SQL injection could happen there.

**Comment by TheRealAgentK** [comment]
Should we report on this then? I can't even think of a "weird" way of abusing the lack of queryparams here.

**Comment by TheRealAgentK** [comment]
The previous comment is for `createODBCDateTime(now())`specially. I suppose there _might_ be scenarios in which one might have an expression without a variable that could cause a problem.

**Comment by justinmclean** [comment]
I can't think of any. The SQL injection is only  likely to only occur with function arguments, form and url scopes anyway and not all variables anyway. I picked the above because it seem fairly common thing to do.

I think another area where it comes up is when setting boolean / int  values like so:
`<cfif someValue>1<cfelse>0</cfif>`

**Comment by TheRealAgentK** [comment]
I guess reporting those scenarios would then still be useful, right? Even though no injection risk. And people can no ignore them using the annotation if they don't want to deal with it.

**Comment by justinmclean** [comment]
The issue with ignoring them it that it ignore them all right including valid ones right?

**Comment by TheRealAgentK** [comment]
no, we've in the meantime have implemented an annotation-based ignore. Check "Annotation-based configuration" in README.

**Comment by TheRealAgentK** [comment]
So, this:
```
<cfquery name="queryName" datasource="#datasourceName#">
update users
<!--- @CFLintIgnore CFQUERYPARAM_REQ --->
set updated = "#createODBCDateTime(now())#"
</cfquery>
```

if you don't want to deal with it.

**Comment by justinmclean** [comment]
Thanks think we can close the one

**Comment by KamasamaK** [comment]
Even with no risk of SQL injection, it's still usually a good idea to parameterize to create a reusable query plan. There are some other minor benefits as well. Is the rule only concerned with SQL injection?

**Comment by TheRealAgentK** [comment]
ok, @justinmclean, ta! :)

**Comment by TheRealAgentK** [comment]
@KamasamaK Yeah, I agree. So, we'll leave as is, it will report and who doesn't want it to, needs to ignore it.
