### ISSUE TITLE
New rule to check assert has message last

### ISSUE THREAD

**Issue by justinmclean** [cflint/CFLint#435]
MXUnit has the message last in it's assert calls unlike some other Junit style frameworks so assertTrue will always pass if you mistakenly put the message first.

**Comment by TheRealAgentK** [comment]
In general: I'm not sure if we should lint 3rd-party frameworks - well, I think I'm actually against that.

However, IF we did this rule, we shouldn't care about MXUnit (which is a dead framework as far as I'm aware), but rather look at Testbox.

**Comment by justinmclean** [comment]
Testbox doesn't use asserts I think?

**Comment by justinmclean** [comment]
Yep it does and yes the message needs to be last so they are constant at least

**Comment by TheRealAgentK** [comment]
Oki, leaves the question: is it CFlint's job to lint framework code? Where to start and to stop here then?

Thinking of Fusebox XML files etc... I'm not sure if that's a good path for CFLint.

**Comment by justinmclean** [comment]
Probably not in that case just close this

**Comment by TheRealAgentK** [comment]
Leaving it open for another couple of days for discussion before I do that - any opinion @ryaneberly @KamasamaK @fingersdancing @mpaluchowski @denuno ?

**Comment by mpaluchowski** [comment]
I'd leave it out too. Or put it on a list of "someday/maybe" features. There's a lot of valuable stuff to lint for, that's related to core CFML.

I know SonarQube for Java has some support for linting jUnit tests, in particular it can check for skipped tests or tests with no assertions. Then again, every testing framework will have its specifics. Perhaps allow for plugins? Then Ortus (makers of TestBox) could perhaps contribute the code needed to lint TestBox, others could contribute theirs etc.

**Comment by KamasamaK** [comment]
I agree that it shouldn't be a "core" rule. The ideal would be as @mpaluchowski said to have a TestBox plugin, but I believe how it works now you would need to build a new JAR with some custom rules.

**Comment by ryaneberly** [comment]
I agree :-)
