### ISSUE TITLE
NullPointerException when calling function 'index' with variable as argument

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#437]
Scanning the following code will cause a `NullPointerException`:

```
component {
    function foo(required any bar) {
        index(bar);
    }
}
```

That appears to be due to the use of `index(bar)`. There's _no_ exception when:

* the function name is different than `index`,
* the function argument is not a variable, ie. is a string,
* the function has no arguments.

**Comment by ryaneberly** [comment]
will be fixed in next release of cfparser
