### ISSUE TITLE
Log currently processed file to console in verbose mode

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#438]
Can we add logging that will, in `-verbose` mode, output the name of the currently processed file to the console? This will be _immensely_ useful in searching for ColdFusion code snippets that trigger bugs in the tool. Right now, whenever there's a parsing error, I only see the error itself and have to dig, often through hundreds of CFML files, to pinpoint the one that's causing the error. Having the name of the file appear just before the error in the console output will make finding it immediate.

**Comment by KamasamaK** [comment]
Support for this also mentioned in Issue #329 and #408

**Comment by TheRealAgentK** [comment]
Done in #329 feature branch.
