### ISSUE TITLE
NullPointerException when string contains closing HTML tag without a matching opening one

### ISSUE THREAD

**Issue by mpaluchowski** [cflint/CFLint#440]
Scanning the following code will cause a `NullPointerException`:

```
component {
  function render() {
    writeOutput("</div>");
  }
}
```

There is **no** exception when:

* there's a preceding `writeOutput("<div>");` line
* the string contains anything else than the closing HTML tag, ie. `writeOutput("div")` (the opening tag, instead of the closing one) or `writeOutput("foo")`.

**Comment by ryaneberly** [comment]
Interesting.  That happens as part of the 'detection' process whether it is pure cfscript or cfml.  The message is now suppressed unless you have vebose enabled.
