### ISSUE TITLE
Excessive memory usage

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#443]
running the latest 1.2.3 build, memory climbs up to 1.5gb pretty quickly, is there a memory leak?

**Comment by TheRealAgentK** [comment]
Can you test your setup with 1.1 and.or 1.2 please and see if it behaves differently now compared to those versions?

**Comment by zspitzer** [comment]
I tried the 1.0.1 release and saw the same behaviour

this is what a run looks like in VisualVM with 1.2.3

![image](https://user-images.githubusercontent.com/426404/29254619-7bf2027c-80db-11e7-842d-e8de44dc42b3.png)

**Comment by TheRealAgentK** [comment]
Cool, thx. At least not freshly introduced. Will do some testing around it.

**Comment by ryaneberly** [comment]
From the little reading I've done ANTLR (cfparser) running at 1.5gb isn't
out of the ordinary.   You can try constraining the max memory on the jvm
if you want to throttle it.
