### ISSUE TITLE
New Rule to detect functions with returntype="numeric" that return bool

### ISSUE THREAD

**Issue by bardware** [cflint/CFLint#447]
I (once more) stumbled over this in some ancient code. I have a function with returntype numeric but I return a boolean value. This worked in ACF before 11; 11 throws.

The code look something like this
```
<cffunction name="myfunc" returntype="numeric">
    <cfset var retval = true>

    <cfquery name="local.qry">
        ...
    </cfquery>
    <cfif local.qry.recordcount EQ 1 AND local.qry.myColumn EQ 1>
        <cfset retval = false>
    </cfif>

    <cfreturn retval>
</cffunction>
```

CFLint has rules to determine complex bools, that means to me you can detect if a variable is assigned a boolean value. 
Now, I wonder if you can check, if the returntype of the function is not "boolean" (like `numeric`) but the `cfreturn` statement returns a var that was assigned a boolean value (or maybe even returns `true`/`false`)?

This would help porting code to a more recent version of ACF.

**Comment by TheRealAgentK** [comment]
I think this would (if at all) only work with very simple cases. In your scenario, @bardware, you've got an explicit .. = false.

But there would be lots of cases in which you'd have something like:

```
<cffunction name="myfunc" returntype="numeric">
    <cfset var retval = "">

    <cfquery name="local.qry">
        ...
    </cfquery>
    <cfif local.qry.recordcount EQ 1 AND local.qry.myColumn EQ 1>
        <cfset retval = somethingelse && somethingcompleteledifferent || maybethis>
    </cfif>

    <cfreturn retval>
</cffunction>
```

I wonder how much we'd be able to reliably track that something ends up being a boolean value throughout the course of execution

**Comment by ryaneberly** [comment]
I agree with @TheRealAgentK, type detection is difficult.  Sorry @bardware , it is a wonderful idea but out of CFLint's scope for the foreseeable future.   Is it ok to close this one?

**Comment by bardware** [comment]
> Is it ok to close this one?

It sure is! Thanks for careing.

**Comment by ryaneberly** [comment]
Thanks @bardware
