### ISSUE TITLE
Deprecated message in stdout

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#448]
Starting with CFLint v1.2.2, the message indicating deprecated features is being written to stdout and breaking anything that expects stdout to just be the standard output. In other words, it is not parsable as JSON or XML with that message.

**Comment by KamasamaK** [comment]
This message was removed in 4330edd. In the future, I think messages like these should be written to `System.err` so as to not break stdout parsing.

**Comment by ryaneberly** [comment]
Sounds like this is resolved.

**Comment by TheRealAgentK** [comment]
Do we still need to keep the messages in place though (writing to System.err) because those features are now due to be removed in 1.4.0?

**Comment by ryaneberly** [comment]
I think they should stay in 1.3.0 and then be dropped.   Is that what you are saying @TheRealAgentK ?

**Comment by KamasamaK** [comment]
Can the message only be written when one of those parameters is defined within the `.cflintrc`? I believe it was previously written regardless.

**Comment by TheRealAgentK** [comment]
@ryaneberly What I meant was that after you removed them in https://github.com/cflint/CFLint/commit/4330edd9676812625c77353d16e30295a572e874 correctly for 1.3.0 - we now have pushed the actual removal to 1.4.0. So, we should bring the messages back, but instead pushing them to .out, to .err.

@KamasamaK Yes, that's a really good suggestion.

**Comment by ryaneberly** [comment]
@TheRealAgentK .  Yes it is removed globally, but I think it is doing what @KamasamaK suggested.
see com.cflint.config.CFLintConfig.setInheritPlugins() and setOutput().  They display a warning on syserr when the setter is invoked.

**Comment by KamasamaK** [comment]
Excellent. So the messages just need to be updated from saying "will be fully removed in CFLint 1.3.0" to "will be fully removed in CFLint 1.4.0".
