### ISSUE TITLE
hanging producing report

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#459]
running the latest dev branch, CFLlint is hanging after completing the scan of 861 files at what i guess is the report generating stage, but the .html report file doesn't get created

The CPU just spins and I'm seeing network traffic (scanning files over a network share)

`java -jar .\CFLint-1.2.3-all.jar -folder .\ -v -rulegroups BugProne -showprogress`

**Comment by zspitzer** [comment]
it finally returns after a very long time, the produced cflint-result.html was 100kb

**Comment by zspitzer** [comment]
seems to be working, I got some other error messages I'll file bugs about

one thing, in the following command line **-folder .\** doesn't match any files, **-folder .\views** does

java -jar ..\CFLint-1.4.0-all.jar -folder .\ -v -rulegroups BugProne

**Comment by ryaneberly** [comment]
added #576 for that.  Thanks @zspitzer
