### ISSUE TITLE
false positive MISSING_VAR with cfdocumentsection name

### ISSUE THREAD

**Issue by zspitzer** [cflint/CFLint#462]
`<cffunction name="createPDF" returntype="any" access="public" output="false">
	<cfdocument format="pdf" bookmark="yes">
		<cfdocumentsection name="section1">
			
		</cfdocumentsection>
	</cfdocument>
</cffunction>`

**Variable section1 is not declared with a var statement.**

**Comment by zspitzer** [comment]
name is also triggering UNUSED_LOCAL_VARIABLE

`<cfcomponent>
	<cffunction name="enumerateLogFiles" access="public" returnType="void" output="false">
		<cfset var q_log_files="">
		<cfdirectory action="LIST" directory="#expandPath('.')#" name="q_log_files" filter="*.log">
	</cffunction>
</cfcomponent>
`

**Comment by ryaneberly** [comment]
the false positive  MISSING_VAR  in cfdocumentsection is fixed.  The other  UNUSED_LOCAL_VARIABLE seems to be valid.  @zspitzer, you are retrieving a file list into q_log_files and not doing anything with it?  or is it retrieved elsewhere in the variables scope?

**Comment by zspitzer** [comment]
trying to remember back to when I found this problem, the above was a simplified test case, which obviously was a bit too simple. I'll see if i can reproduce it again

**Comment by ryaneberly** [comment]
Closing this issue since the main item on it is resolved and included in 1.3.0.  @zspitzer feel free to raise another if you get the details on the UNUSED_LOCAL_VARIABLE example.
