### ISSUE TITLE
Speeding up CFLint

### ISSUE THREAD

**Issue by laserbyte** [cflint/CFLint#47]
Do you have any suggestions for speeding up CFLint? I would really like to use it as part of the SublimeLinter package but with the lint mode set to background every time I save a file I get the spinning beach ball for a few seconds and the user interface is frozen. Presumably the plugin is running cflint and waiting for that to return which ties up the user interface. I base this assumption on when I run CFLint from the command line it takes about the same amount of time to process the file as the interface is frozen when I save.

**Comment by ryaneberly** [comment]
The antlr4 version (master branch in cfparser and cflint projects), is
significantly faster over a large fileset (about 10x in my experience).
We're working through getting it release ready, but I don't know how soon
that will happen.

You can build it yourself if you want to try it out.

The only alternative I know of is to somehow keep the cflint/java process
alive in the background and communicate between the plugin and cflint
processes somehow when a save happens.
