### ISSUE TITLE
Latest CFLint unable to handle any file

### ISSUE THREAD

**Issue by tonymorelli73** [cflint/CFLint#470]
I was trying to upgrade from CFLint 1.0.1 to CFLint 1.2.0, and am getting errors on every file (see below):
```
Severity:ERROR
Message code:FILE_ERROR
	File:D:\SonarQube\SonarQubeWorkingCopy\CMS\branches\dev_5.7.0\VTS\Main\work\work_js.cfm
	Column:1
	Line:1
		Message:Illegal/unsupported escape sequence near index 1
\R
 ^
		Variable:'null' in function: null
		Expression:
```
Is there any specific parameter that needs to be passed to CFlint to indicate the file encoding type?   

When I run CFLint 1.0.1 against the same code with the same command line, I don't receive these errors.
```
java -jar CFLint-1.0.1-all.jar -folder D:\SonarQube\SonarQubeWorkingCopy\CMS\branches\dev_5.7.0\ -verbose -e -text -textfile .\CFLint101-CMS_Errors.log

java -jar CFLint-1.2.0-all.jar -folder D:\SonarQube\SonarQubeWorkingCopy\CMS\branches\dev_5.7.0\ -verbose -e -text -textfile .\CFLint120-CMS_Errors.log
```

**Comment by ryaneberly** [comment]
Please try the latest 1.2.x version.
https://github.com/cflint/CFLint/releases/download/CFLint-1.2.3/CFLint-1.2.3-all.jar

**Comment by tonymorelli73** [comment]
I was trying to test out CFLint 1.2.0 becuase it's the version that's built into the latest Coldfusion Sonarqube Plugin that was causing some issues.   It looked like CFLint was having issues within the Plugin, so I was attempting to test CFLint standalone.

In testing CFLint 1.2.3, the same issue is occuring as reported for CFlint 1.2.0.
```
java -jar CFLint-1.2.3-all.jar -folder D:\SonarQube\SonarQubeWorkingCopy\CMS\branches\dev_5.7.0\ -verbose -e -text -textfile .\CFLint123-CMS_Errors.log
```
```
Severity:ERROR
Message code:FILE_ERROR
	File:D:\SonarQube\SonarQubeWorkingCopy\CMS\branches\dev_5.7.0\VTS\Main\work\work_js.cfm
	Column:1
	Line:1
		Message:Illegal/unsupported escape sequence near index 1
\R
 ^
		Variable:'null' in function: null
		Expression:
```
The stack trace is always the same:
```
Logging Error: FILE_ERROR
java.util.regex.PatternSyntaxException: Illegal/unsupported escape sequence near
 index 1
\R
 ^
        at java.util.regex.Pattern.error(Pattern.java:1924)
        at java.util.regex.Pattern.escape(Pattern.java:2416)
        at java.util.regex.Pattern.atom(Pattern.java:2164)
        at java.util.regex.Pattern.sequence(Pattern.java:2046)
        at java.util.regex.Pattern.expr(Pattern.java:1964)
        at java.util.regex.Pattern.compile(Pattern.java:1665)
        at java.util.regex.Pattern.<init>(Pattern.java:1337)
        at java.util.regex.Pattern.compile(Pattern.java:1022)
        at java.lang.String.split(String.java:2313)
        at java.lang.String.split(String.java:2355)
        at com.cflint.CFLint.scan(CFLint.java:259)
        at com.cflint.CFLint.scan(CFLint.java:249)
        at com.cflint.CFLint.scan(CFLint.java:249)
        at com.cflint.CFLint.scan(CFLint.java:249)
        at com.cflint.CFLint.scan(CFLint.java:249)
        at com.cflint.CFLint.scan(CFLint.java:186)
        at com.cflint.main.CFLintMain.execute(CFLintMain.java:437)
        at com.cflint.main.CFLintMain.main(CFLintMain.java:282)
```
It's always reporting a ` \R` is found at Column 1 Line 1.  Which is why I am thinking it has something to do with encoding.   I need to talk to my ColdFusion developers to see what's being done to save the files and encoding settings, but it's odd that the different versions of CFLint behave this differently on the files.

**Comment by denuno** [comment]
I'm pretty sure the `\\R` needs Java 8, so maybe check that you're using a recent JRE?

**Comment by tonymorelli73** [comment]
Does it matter which revision?   I'm checking on the JRE8 version we have.

**Comment by denuno** [comment]
I think so long as it's 8 it should be good, and it might be something else, but the version of the JRE is a good thing to verify anyway.

**Comment by tonymorelli73** [comment]
Thanks for the info.  When I forced the command line to explicitly use the Java in the jre8 folder vs using the default path, it appears to be working as I was expecting.

**Comment by ryaneberly** [comment]
Good call, Denny.  Thanks!

**Comment by TheRealAgentK** [comment]
Yes - I can't remember where ***exactly*** we made a change to some of the RegExp handling, bit I think for 1.1. we changed to an only-Java 8 compatible syntax.
