### ISSUE TITLE
Variable Query is not a valid name. Please use CamelCase or underscores.

### ISSUE THREAD

**Issue by isaac-mercieca** [cflint/CFLint#472]
When using one of the below statements, it is being listed under VAR_INVALID_NAME however this is not the case because both Query and PDF are components.

`var objQuery= new Query();`
`var objPdf= new Pdf();`

Should the VAR_INVALID_NAME plugin check if the "variable" is after the new command?

**Comment by ryaneberly** [comment]
Fixed in dev for 1.3.0.  Thanks @isaac-mercieca
