### ISSUE TITLE
Maven Integration

### ISSUE THREAD

**Issue by isaac-mercieca** [cflint/CFLint#473]
@ryaneberly

I have created a new repository https://github.com/isaac-mercieca/CFLint-Maven-Plugin, where I have a commited an early prototype version of a maven plugin for cflint. I was wondering it would be possible to split the CFLintMain so that the execution configuration will consist of the configuration of an new class instance which can be invoked from the CFLintMain class but also outside the project itself when included as another pproject's dependency. For my case I ended up duplicating most of the base logic in CFLintMain, would you approave if I make this more modular for such cases. Also if you have any ideas for the plugin it would be realy helpful thanks.

**Comment by ryaneberly** [comment]
@isaac-mercieca Thanks for reaching out.  I reaching made an attempt at an 'api' for cflint that does exactly what you are asking - I think.  See this branch
https://github.com/cflint/CFLint/tree/api2

**Comment by ryaneberly** [comment]
See the API section on the README of that branch

**Comment by ryaneberly** [comment]
FYI 
api2 has been merged to dev
