### ISSUE TITLE
IntelliJ Plugin CFLint Support

### ISSUE THREAD

**Issue by isaac-mercieca** [cflint/CFLint#474]
@TheRealAgentK, I am interested in a CFLint plugin for IntelliJ, how can I contribute?

**Comment by justinmclean** [comment]
Re CFLint plugin for intelliJ you can should be able to user the sonar cube plugin as it can use CFLint under the hood

**Comment by rcastagno** [comment]
Last time I tried, the SonarQube plugin was not usable for CFML.
Anyway, it would be a workaround, not a solution. An eventual lint plugin should work without dependency on SonarQube.

**Comment by ryaneberly** [comment]
you could look at what was done to integrate VSC and CFLint

**Comment by KamasamaK** [comment]
As far as integration, VSC is just using the command line and parsing the results. For a better solution, it might be best to hold off until the API lands.

Either way, you should check out the source for some of the existing [third-party lint plugins](https://plugins.jetbrains.com/search/idea?correctionAllowed=true&search=lint). There are also some more official plugins such as [stylelint](https://github.com/JetBrains/stylelint) and [tslint](https://github.com/JetBrains/intellij-plugins/tree/master/tslint).
