### ISSUE TITLE
Vim syntastic support

### ISSUE THREAD

**Issue by displague** [cflint/CFLint#48]
I've seen references to people using vim sytantastic integration with cflint but can't find any pointers.

It would be great if the documentation included instructions (or config files) to make this simpler.

I think cflint may need a more terse and predictable output format for vim to latch on to line specific errors, but that may just be my ignorance (`|grep|sed` may do the trick).

I've been using this, but it is ugly:

~/.vim/ftplugin/cf.vim
```
function! Lint()
	! /home/marques/.local/bin/cflint -file "%" -text
	cwindow
endfunction

if !exists("autocommands_loaded")
	let autocommands_loaded = 1
	autocmd BufWritePost *.cfm,*.cfc call Lint()
endif
" noremap <leader>l :w!<CR>:!clear;/home/marques/.local/bin/cflint -file "%" -text<CR>
```

**Comment by jphustman** [comment]
That is simple, but it works!  I've been trying to get it to work in Syntastic as well, although I don't have it working----yet.  I set up a repo so we don't fill CFLint issues with Syntastic stuff, maybe we can get it working: https://github.com/jphustman/cflint-syntastic

**Comment by ryaneberly** [comment]
I created
https://github.com/cflint/cflint-syntastic
Jeremey you have admin privs.

if you want it.  if not,I'll remove it again.

**Comment by jphustman** [comment]
Awesome, thanks!

**Comment by displague** [comment]
Is cflint's output similar to or modeled after an existing checker?https://github.com/scrooloose/syntastic/tree/master/syntax_checkers

**Comment by jphustman** [comment]
cflint gives a lot of information, but it's structured enough that you can separate out it's parts with 'let errorformat =' , just looking through some of the checkers it looks like the https://github.com/scrooloose/syntastic/blob/master/syntax_checkers/fortran/gfortran.vim is pretty similar.

**Comment by ryaneberly** [comment]
Adding another output format is easy to do.  What would an ideal output look like for syntastic to consume?

**Comment by displague** [comment]
The format doesn't seem to be a problem after-all, `let errorformat=` can handle many things.  I believe it's grokking fine now (although I haven't given it a real-world test).

I want to try some of the `cflint` tests against https://github.com/cflint/cflint-syntastic (do you have these cfm tests somewhere outside of the java functions?)

**Comment by displague** [comment]
This makes me so happy...

![image](https://cloud.githubusercontent.com/assets/317653/7335150/fe78c154-eb78-11e4-8201-c4ef9e7bab74.png)

**Comment by ryaneberly** [comment]
@displague All the tests are currently embedded in java code.

**Comment by ryaneberly** [comment]
merged README from @displague. .
