### ISSUE TITLE
MISSING_VAR reports cfmail() attributes

### ISSUE THREAD

**Issue by eppinger** [cflint/CFLint#482]
sample:
  cfmail( from="test@test.de", to="test@test.de" subject="#subjectText#" type="html" ){
             }

reports 
Variable from is not declared with a var statement., etc

**Comment by eppinger** [comment]
same problem with this syntax:;
`mail from="test@test.de", to="test@test.de" subject="#subjectText#" type="html"{}`

**Comment by ryaneberly** [comment]
@eppinger  or @TheRealAgentK, is that syntax with missing commas legit?
i.e. we should be able to parse:
cfmail( from="test@test.de", to="test@test.de" subject="#subjectText#" type="html" ){
}
as is?

Does this apply to ALL function calls?

**Comment by KamasamaK** [comment]
@ryaneberly This is another difference between ACF and Lucee. ACF requires the commas, but Lucee does not.

**Comment by ryaneberly** [comment]
Thanks @Kamasamak, Does this apply to all functions, or just tags?

**Comment by KamasamaK** [comment]
This appears to only apply to tags.

**Comment by ryaneberly** [comment]
I added tests to confirm,  this seems to be fixed in dev with the latest cfparser
