### ISSUE TITLE
MISSING_VAR reports cfwddx() attributes

### ISSUE THREAD

**Issue by eppinger** [cflint/CFLint#483]
sample
cfwddx(action="cfml2wddx", input="#attribs#" output="attribsWDDX");

reports
Variable action is not declared with a var statement., etc

**Comment by TheRealAgentK** [comment]
Hey Andreas, thx for logging these. I wonder if this and #482 is a general problem with this kind of cfscript syntax in the parsing process. 

From what I can see is that it thinks cfwddx and cfmail in your other example are user functions and then looks for a named arguments action etc --- that is never defined as a local variable.

@ryaneberly - would that a fair assessment?

**Comment by eppinger** [comment]
i think it is tag specific.

throw message=""  reports var not declared
cfthrow(message="") is ok

and #482 is for both variants
cfmail() and mail reports var not declared

**Comment by ryaneberly** [comment]
I will look at what we did for throw and see what can done about this one.

**Comment by ryaneberly** [comment]
Does anyone have the spec for the rather awkward form:
tag attribute=value
for all of the cftags?

It's going to take hard coding those special cases in the parser as far as I can tell.

**Comment by TheRealAgentK** [comment]
"yay" :-/

I'm not sure if there IS a spec. IIRC the official line from Adobe was that all tags can be used this way with all attributes each tags supports.

Is that correct, @eppinger ?

**Comment by eppinger** [comment]
the tag attribute=value syntax was the first lucee implementation in cfscript

Adobe uses in cf11+  the cftag(attribute=value) syntax.

Lucee supports now both variants.

https://helpx.adobe.com/coldfusion/cfml-reference/coldfusion-tags/tags-r-s/cfscript.html
https://helpx.adobe.com/coldfusion/developing-applications/the-cfml-programming-language/extending-coldfusion-pages-with-cfml-scripting/what-is-supported-in-cfscript.html

**Comment by ryaneberly** [comment]
Ah, I thought Adobe led the way in interesting language decisions...   Thanks @eppinger I'll see what we can do in cfparser.

**Comment by ryaneberly** [comment]
cfparser 2.6.0 is out, and I believe the issues in this task are resolved.

**Comment by ryaneberly** [comment]
This will be included in 1.3.0
