### ISSUE TITLE
Example for excluding multiple rules

### ISSUE THREAD

**Issue by rsmolkin** [cflint/CFLint#485]
I tried the below in VSCode, but it doesn't seem to be excluding anything...
```
{
  "output" : [ ],
  "rule" : [ ],
  "excludes" : [ 
    {
      "code" : "VAR_HAS_PREFIX_OR_POSTFIX"
    },
    {
      "code" : "MISSING_VAR"
    },
    {
      "code" : "VAR_INVALID_NAME"
    },
    {
      "code" : "MISSING_VAR"
    },
    {
      "code" : "FUNCTION_TOO_COMPLEX"
    }
  ],
  "includes" : [ ],
  "inheritParent" : false,
  "inheritPlugins" : true
}

If I restart VSCode when there is a .cflintrc file, it doesn't seem to do any linting.  If I remove it, it processes all rules, but I'm trying to find a way to exclude some.

**Comment by TheRealAgentK** [comment]
I'm not sure what's going on specifically with VSCode and that might be a totally separate issue.

For a start: could you please test the .cflintrc file with plain command-line CFLint in your setup and let us know if that creates the results you expect?

**Comment by ryaneberly** [comment]
I would be inclined to move some of the rather opinionated naming rules to
be disabled by default in a future release - there are more important
things to lint.  IMO.  Thoughts?

**Comment by TheRealAgentK** [comment]
Was this comment supposed to go towards #480 ? :)

Anyway - I'd agree, we should have a core set of important rules to run by default and anything else needs to be manually added.

**Comment by ryaneberly** [comment]
Probably more in line with #480.  good point.

**Comment by KamasamaK** [comment]
It's difficult to say where the issue lies at this point, but since VS Code was mentioned in the issue linked above, I asked him to open an issue on that repo so I could look into it with more information, but I think there was misunderstanding.

**Comment by rsmolkin** [comment]
@TheRealAgentK I just tried it with command line.  The resulting file included warnings for FUNCTION_TOO_COMPLEX and SCOPE_ALLCAPS_NAME while I have them excluded in the .cflintrc:
```
{
  "rule" : [ ],
  "excludes" : [
    {"code": "VAR_HAS_PREFIX_OR_POSTFIX"},
    {"code": "MISSING_VAR"},
    {"code": "VAR_INVALID_NAME"},
    {"code": "MISSING_VAR"},
    {"code": "FUNCTION_TOO_COMPLEX"},
    {"code": "VAR_IS_TEMPORARY"},
    {"code": "SCOPE_ALLCAPS_NAME"}
  ], 
  "includes": [ ],
  "inheritParent" : true
}

**Comment by rsmolkin** [comment]
Should putting codes under Excludes, exclude those from Warning and Info messages as well?

**Comment by KamasamaK** [comment]
I notice you changed `inheritParent` from `false` to `true`. Did you notice that making any difference?

**Comment by rsmolkin** [comment]
No, I was just trying to play around with the settings.

**Comment by rsmolkin** [comment]
Are you able to get any rules to be excluded on your end?

**Comment by ryaneberly** [comment]
@rsmolkin, when I run your example I get a 
"could not read config file" on the stderr.

Strangely it works if I remove the MISSING_VAR exclusion!
