### ISSUE TITLE
Why AVOID_USING_ARRAYNEW and AVOID_USING_STRUCTNEW?

### ISSUE THREAD

**Issue by JuanTorr** [cflint/CFLint#486]
Hello, I'm new with coldfusion, so I configured this linter with VSCode to know some good pratices. But I don't know the reason to avoid using those functions.

**Comment by TheRealAgentK** [comment]
It's better practice to use the literal syntax:

```
anArray = [];
aStuct = {};
```

**Comment by JuanTorr** [comment]
I thought it had something to do with performance. 

I have another question.
I have a CFM file that starts with <!DOCTYPE html>
And I get the error FUNCTION_TOO_COMPLEX. Is there a better way to start the file or is this a bug?

**Comment by TheRealAgentK** [comment]
It’s hard to say what the problem is without seeing your full file.

**Comment by ryaneberly** [comment]
There is likely a function in your cfm file that the tool identifies as excessively long.   If this is not the case, please reopen.
