### ISSUE TITLE
unused var, but it is used.

### ISSUE THREAD

**Issue by KrunchMuffin** [cflint/CFLint#493]
so it seems if I do something like this

    var foo = "";
    transaction {
        foo = 1; 
        ...other stuff...
    }

I get a cflint error saying `foo` is unused. If I put it inside the `transaction` error goes away. 
I don't know if this is a bug or actually a real case scenario. Never heard that variables made outside a transaction are not available inside a transaction, but maybe it is the case.
Anyone know for sure?

**Comment by ryaneberly** [comment]
cflint is not making a statement about the nature of transactions and variables.  I think this is a CFLint false positive bug.

**Comment by KamasamaK** [comment]
As I understand the rule, assignment does not constitute usage, so I would expect it to also report within the `transaction` as presented. I'm not sure I would call the issue a false positive without seeing the case where it fails.

**Comment by KrunchMuffin** [comment]
here u go

![image](https://user-images.githubusercontent.com/1037197/34132469-ff9a7104-e41d-11e7-9328-94af3e33ba08.png)

**Comment by KamasamaK** [comment]
So because it is returned, it should definitely be seen as used. 

Regardless, I am still confused. You said when it's put inside the `transaction` error goes away, but you are also saying that it is reporting it here where it is in a `transaction`. What exactly makes the error go away?

**Comment by KrunchMuffin** [comment]
No, if I put set the var inside the `transaction` it goes away
![image](https://user-images.githubusercontent.com/1037197/34138656-a66a38aa-e43e-11e7-89b6-d38f3116db37.png)

**Comment by KamasamaK** [comment]
I see. When it's declared in the `transaction` block then it's fine. Thanks for clarifying.

**Comment by ryaneberly** [comment]
hmm, first while blocks, and now transaction blocks.   Both were being skipped by cflint.  I believe any others should be resolved in a generic fashion now.

This is fixed in dev branch, will be available in 1.3.0
