### ISSUE TITLE
Another var scoped bug?

### ISSUE THREAD

**Issue by KrunchMuffin** [cflint/CFLint#501]
Looks like a bug to me. Says I am not using it anywhere and also says that it isn't var'd

![image](https://user-images.githubusercontent.com/1037197/34322039-d033539c-e7ea-11e7-90a9-291e17e8685d.png)

**Comment by KamasamaK** [comment]
That is two different variable names. The query one is not var'd and the var'd one is not used.

**Comment by KrunchMuffin** [comment]
Damnit sorry
