### ISSUE TITLE
Parameter name standardization

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#503]
Now that parameters are more user-facing, I think the naming convention of parameters should be standardized. I prefer them being camelCase but some of them are PascalCase.

**Comment by KamasamaK** [comment]
@ryaneberly Thanks! I think there were some unintended changes to setters in [`ValidName.java`](https://github.com/cflint/CFLint/blob/7eb424057b327151fcbdbcb757c94ad4548fd58e/src/main/java/com/cflint/plugins/core/ValidName.java).

**Comment by ryaneberly** [comment]
fixed in dev.  Thanks @KamasamaK .
