### ISSUE TITLE
Describe built-in rules more precisely

### ISSUE THREAD

**Issue by SebastianZ** [cflint/CFLint#505]
https://github.com/cflint/CFLint/blob/master/RULES.md lists all the different built-in rules and rule groups. Currently, this list only contains a one-line description for each rule.

Though this description lacks any details. E.g. the description for VAR_INVALID_NAME is "Variable has invalid name.".

As a user, I'd like like to have a more verbose description explaining what exactly is considered an invalid variable name by default and a short description of each parameter that can be adjusted to customize the rule.

Sebastian

**Comment by ryaneberly** [comment]
java -jar CFLint-xxx.jar -markdown

generates the RULES.MD automatically.

**Comment by SebastianZ** [comment]
>     java -jar CFLint-xxx.jar -markdown
> 
> generates the RULES.MD automatically.

Thank you for the hint! I guess you meant `-rules`, because `-markdown` isn't recognized, as far as I can see. That helps at least to get to know the latest built-in rule set.

Sebastian

**Comment by ryaneberly** [comment]
@SebastianZ, you're too fast.  :)  -markdown is merged into dev and master now.

The rules could use some better documentation as you mentioned, so I'll leave this open.  But getting the parameters in one (readable) place is a start.

**Comment by TheRealAgentK** [comment]
Ah @ryaneberly - ignore my question in #492 - just found this :)
