### ISSUE TITLE
java cast exception when parsing include where template argument is a function result

### ISSUE THREAD

**Issue by steveleve** [cflint/CFLint#506]
tried this in 1.2.0, 1.2.3, and 1.3.0 with very similar results.

```
	// fails with java exception 
	include getTemplatetoInclude();
```
`java.lang.ClassCastException: cfml.parsing.cfscript.CFFunctionExpression cannot be cast to cfml.parsing.cfscript.CFStringExpression`

attached demo 
[CfLint.zip](https://github.com/cflint/CFLint/files/1589896/CfLint.zip)

incidentally; is there a good way to skip an include or a block? 
in jshint we have `jshint ignore:start` to `jshint ignore:end`
I did try the `jshint ignore:line` syntax, but that didn't seem to do the trick

I got into this because of this error being thrown in an include, but would be happy to have the parser omit the include in this case. 

Thanks;

**Comment by ryaneberly** [comment]
@steveleve .  Thanks for reporting this bug with clear examples.  It is fixed and will be included in 1.3.0 

There was no way to ignore that exception.
