### ISSUE TITLE
maven install should install the binaries in a usable way

### ISSUE THREAD

**Issue by displague** [cflint/CFLint#51]
Following `mvn clean install` I currently symlink ~/src/CFLint/target/appassembler/bin/cflint to somewhere in my path (~/.local/bin).  I also have to make the binary executable `chmod a+x  ~/src/CFLint/target/appassembler/bin/cflint`.  These steps (setting permissions, and installing the appassembler artifacts) should be part of the install.

**Comment by ryaneberly** [comment]
It looks like appassembler-maven-plugin resolved this.
http://jira.codehaus.org/browse/MAPPASM-54

Try using version 1.10 of the appassembler-maven-plugin in the cflint/pom.xml

**Comment by displague** [comment]
The execute bit is set with 1.10 but that doesn't address how one gets the appassembler artifacts into usable locations.

**Comment by displague** [comment]
Does it have something to do with:
http://mojo.codehaus.org/appassembler/appassembler-maven-plugin/create-repository-mojo.html#assembleDirectory
is there a way to `mvn clean install --assembleDirectory=~/.local`  (or `/usr/local/` or `/opt/` as others may choose) ?

**Comment by ryaneberly** [comment]
you can do that:
mvn clean install D-assembleDirectory=~/.local

it will create files in bin/ lib/ and etc/ folders.

**Comment by displague** [comment]
Thanks!  `mvn clean install -D assembleDirectory=~/.local` worked (had to remove the dash after `-D`).

I think it's worth noting in the build instructions.
