### ISSUE TITLE
<cfcookie name...> fires MISSING_VAR

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#518]
1.4.0 in dev branch.

```<cfcookie name="_dist" value="" expires="now" httponly="true">```

I don't think _dist needs to be var'ed.

**Comment by KamasamaK** [comment]
If I understand how this tag/attribute works, I agree. Oddly, I do not see `cfcookie` in the [list of tags to check for `name`](https://github.com/cflint/CFLint/blob/b7091f020dbacf47bd40c02230a3bcc9995acd51/src/main/java/com/cflint/plugins/core/VarScoper.java#L28), so I'm not sure what's causing this.

**Comment by ryaneberly** [comment]
Thanks @TheRealAgentK ,  the dictionary specifies @name as a return from cfcookie, which is technically true, but not in terms of how we use it (that it creates a variable).
