### ISSUE TITLE
No arguments being passed into CFLint

### ISSUE THREAD

**Issue by TheRealAgentK** [cflint/CFLint#521]
Currently, if someone just runs:

```java -jar ./CFLint-1.4.0-SNAPSHOT-all.jar ```

they're getting the help prepended with 

```Set -folder or -stdin to use CFLint```

But is that the right messaging? For instance, it can most certainly being used with -file alone, can't it? What's the minimum (set of) cli argument(s) that needs to be supplied?

**Comment by ryaneberly** [comment]
-folder and -file are essentially aliases

**Comment by TheRealAgentK** [comment]
I will fix the wording of this message in my branch for #329.
