### ISSUE TITLE
Add support for struct literal using square brackets

### ISSUE THREAD

**Issue by micahknox** [cflint/CFLint#534]
Lucee supports the use of square brackets as opposed to curly brackets when defining a struct literal. This creates an ordered structure and preserves the order of the keys. Currently the CFLint parser sees this as incorrect synatx and flags it as an error. I propose support be added for this syntax. Here's an example of some code that produces this error:
`var orderedStruct = [
			keyA: 'value',
			keyB: 'value'
		]`

**Comment by KamasamaK** [comment]
ACF2016 also supports [this syntax](https://helpx.adobe.com/coldfusion/2016/language-enhancements.html#Literalsyntax).

**Comment by KamasamaK** [comment]
Also, be sure to consider the empty ordered struct literal:
var orderedStruct = [:]

**Comment by KamasamaK** [comment]
Depends on cfparser/cfparser#124

**Comment by ryaneberly** [comment]
fixed with cfparser 2.10.0.
