### ISSUE TITLE
VAR_INVALID_NAME for scoped variable

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#537]
The following code triggers a VAR_INVALID_NAME issue with the message "Variable local.kvPair is not a valid name. Please use camelCase or underscores." It is using camelCase, but the problem seems to be that it is including the `local.` as part of the variable name.

```
<cfloop list="#arguments.parseData#" delimiters="&" index="local.kvPair">
	<cfset local.keyStr = listFirst(local.kvPair, "=")>
	<cfset local.valStr = listLast(local.kvPair, "=", true)>
	// Do stuff
</cfloop>
```

**Comment by CH1tcg** [comment]
Same, agreed
