### ISSUE TITLE
thread / cfthread scope not ignored as expected

### ISSUE THREAD

**Issue by gpickin** [cflint/CFLint#538]
Certain thread and cfthread syntax are being flagged for var scoping, 

`cfthread['CategoryAvailabilityEX'] = CreateObject()`

`thread.InErrorState = false;`

Sorry if this is a duplicate. I couldn't find the other issue to add onto.

**Comment by KamasamaK** [comment]
The issue with `thread` has been corrected, but `cfthread` still gives MISSING_VAR.

[Here](https://helpx.adobe.com/coldfusion/developing-applications/developing-cfml-applications/using-coldfusion-threads/using-thread-data.html) is an article discussing the use of `cfthread` as a scope.

**Comment by ryaneberly** [comment]
fixed cfthread scope false positive in dev branch
