### ISSUE TITLE
Misc. Parsing Error?

### ISSUE THREAD

**Issue by jerronjames** [cflint/CFLint#54]
Misc Violation in CFLint-result:

	Error	

      In file \TaskGateway.cfc, line 57
      In c:\v11\server\webapps\ROOT\WEB-      INF\railo\components\railo\extension\gateway\TaskGateway.cfc
      At line : 57
      Expression: [@209,1518:1521='file',<88>,57:56]

Function being parsed:

      23:     public function start() {
      24: 
      25:         while ( variables.state == "stopping" )
      26:             sleep( 10 );
      27: 
      28:         variables.state = "running";
      29: 
      30:         log text="Event Gateway #variables.id# started" file=this.logfile;
      31: 
      32:         while ( variables.state == "running" ) {
      33: 
      34:             try {
      35: 
      36:                 this.PerformTask();
      37:             }
      38:             catch ( ex ) {
      39: 
      40:                 log text="Event Gateway #variables.id# error: #ex.message#" file=this.logfile type="error";
      41:             }
      42: 
      43:             // sleep( variables.interval );
      44:             
      45:             var ts = getTickCount();
      46:             
      47:             while( getTickCount() - ts < variables.interval ) {
      48: 
      49:                 sleep( 1000 );
      50: 
      51:                 if ( variables.state != "running" )
      52:                     break;
      53:             }
      54:         }
      55: 
      56:         variables.state = "stopped";
      57:         log text="Event Gateway #variables.id# stopped" file=this.logfile;
      58:     }

**Comment by ryaneberly** [comment]
What is that crazy syntax?

         log text="Event Gateway #variables.id# started" file=this.logfile;

Can you point me it's documentation.

**Comment by ryaneberly** [comment]
found it:
http://www.getrailo.org/index.cfm/whats-up/railo-40-released/features/tags-in-cfscript/
 
    For a while now, Railo has had the ability to use most of the built-in tags within the <cfscript> tag. 
    All you have to do is remove the <cf at the start and usually, if it is a single line replace the > at 
    the end with ;....

    How about tags that wrap some kind of content? Tags like <cfmail>, <cfloop> and <cfquery>? 
    They are just as easily used with {} brackets!

Maybe just me, but seems an arbitrary way to make the language more complex.  What is wrong with functions?

**Comment by jerronjames** [comment]
Oh, I should point out. That code is actually in the railo code base, not ours. I just thought I’d document it.

**Comment by ryaneberly** [comment]
https://wikidocs.adobe.com/wiki/display/coldfusionen/Tags#Tags-Tagwithoutbodies

**Comment by ryaneberly** [comment]
log is implemented, but there is a whole mess of tags to handle this way.

**Comment by jjames967** [comment]
I'm wondering if there's a simple way to parse and flag them? Personally, I think they should be flagged critical to not use. However, the question remains... simple way to identify them?

**Comment by ryaneberly** [comment]
the same logic was used to define the cfscript version of
cfcomponent

identifying them should be relatively simple.  There's just a lot of busy
work putting the keywords into the lexer.
.

**Comment by ryaneberly** [comment]
fixed.
