### ISSUE TITLE
ARGUMENT_INVALID_NAME misreporting on acronyms

### ISSUE THREAD

**Issue by lmajano** [cflint/CFLint#541]
As per Java coding standards a variable called `APIKey` is valid since all acronyms are uppercase regardless of position. However the rule above does not account for it and reports it as invalid.  This might be tricky since you need to parse for well know acronyms to differentiate.

**Comment by KamasamaK** [comment]
Can you please provide a source for this Java coding standard?

**Comment by lmajano** [comment]
Actually, I stand corrected. I have searched and searched where we started with this over years of coding standards and cannot find it, but the opposite.  So I have updated the ortus coding standards to match and will close this.
