### ISSUE TITLE
UNUSED_METHOD_ARGUMENT: Case not being retained

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#545]
The letter case of the argument is not being retained for the message of `UNUSED_METHOD_ARGUMENT`. It is being represented as all lowercase in the message regardless of how it is written.

Example
```
function foo(any bAr) {
	return;
}
```
Reports the message as "Argument bar is not used in function. Consider removing it." and variable as "bar".

**Comment by ryaneberly** [comment]
fixed in 1.4.1
