### ISSUE TITLE
Support running different rules in different scenarios / environments

### ISSUE THREAD

**Issue by jimpriest** [cflint/CFLint#548]
I know I can nest .cflintrc files - but what I'd like to be able to do is define different rules within that rule file for different scenarios or environments.  

For example
* In my editor I only want to run a handful of rules for common issues
* In my pre-commit hook I want to run more rules for a more thorough check
* In my Jenkins job I want to run all the rules

I thought I could do this now with a combination of rule files and declaring rules on the command line but I think the rule file always takes precedence - from the docs:

*If you exclude a rule at the command line level, but a .cflintrc adds it back in, it will fire for source files in that part of the source tree.*

I've been using Robot Framework (a python testing framework) and they support 'tags' within each test which grant you this flexibility.  

I have no idea how feasible this is to implement from a technical standpoint  :)

**Comment by ryaneberly** [comment]
if you specific 
-environment <env name> 
on the command line, only files of the form.<env name>-cflintrc will apply

**Comment by KamasamaK** [comment]
I would prefer a suffix to a prefix. e.g. `.cflintrc-hook`, `.cflintrc-cicd`

**Comment by ryaneberly** [comment]
@KamasamaK .  Agreed.  It's done.  thanks for the input.
