### ISSUE TITLE
Support for CF 11

### ISSUE THREAD

**Issue by leslies61801** [cflint/CFLint#55]
Hi,

Does CFLint support CF 11? 

Regards,

Leslie

**Comment by displague** [comment]
The short answer is yes.  CFLint should parse CF11.

The finer details of what, when, and how should get included in the README
or wiki.

**Comment by ryaneberly** [comment]
http://www.adobe.com/devnet/coldfusion/articles/language-enhancements.html

* script support for built in tags, not yet supported
      * They chose a different syntax from railo, which is currently supported.
* Script support for Custom tags - not yet supported 
* Member Functions for CF data type - supported
* Elvis Operator  - not yet supported I think, I'd need to test it.

**Comment by ryaneberly** [comment]
added elvis operator to cfparser
https://github.com/cfparser/cfparser/commit/49101b7d49109e421cc7229ac3c6bbe07eb28615
