### ISSUE TITLE
Add queryExecute to QueryParamChecker

### ISSUE THREAD

**Issue by jsteinshouer** [cflint/CFLint#554]
I am considering creating a pull request to add the `queryExecute` method to this for checking for SQL parameters:

https://github.com/cflint/CFLint/blob/5b8bc59df6fa0c07296e8710eb852c67c6d9ce67/src/main/java/com/cflint/plugins/core/QueryParamChecker.java#L23

However the default message for `QUERYPARAM_REQ` is `setSql() statement should use .addParam() instead of #'s name=\"${variable}\"`. Would it be preferable to change the default message or add a new code specific to `queryExecute`? Great tool by the way. Thanks!

**Comment by ryaneberly** [comment]
I'm fine with changing the message to something like: "Use query parameters for variables".  Thanks!
