### ISSUE TITLE
Example `.cflintrc` in readme.md is not valid when run.

### ISSUE THREAD

**Issue by cybersonic** [cflint/CFLint#559]
The example `.cflintrc` as defined in `README.md` is as follows:
```
{
    "output" : [ ],
    "rule" : [ ],
    "excludes" : [ ],
    "includes" : [ {
        "code" : "FUNCTION_HINT_MISSING"
    } ],
    "inheritParent" : false,
    "inheritPlugins" : true,
    "parameters" : {}
}
```
When you run it with `1.3.0` you get the following errors:

> DEPRECATED: The use of "output" have been marked as deprecated in CFLint 1.2.x and support for them will be fully removed in CFLint 1.4.0. Please remove the settings from your configuration file(s). Run CFLint in verbose mode for config file location details.
> DEPRECATED: The use of "inheritPlugins" have been marked as deprecated in CFLint 1.2.x and support for them will be fully removed in CFLint 1.4.0. Please remove the settings from your configuration file(s). Run CFLint in verbose mode for config file location details.
> DEPRECATED: The use of "output" have been marked as deprecated in CFLint 1.2.x and support for them will be fully removed in CFLint 1.4.0. Please remove the settings from your configuration file(s). Run CFLint in verbose mode for config file location details.
> DEPRECATED: The use of "inheritPlugins" have been marked as deprecated in CFLint 1.2.x and support for them will be fully removed in CFLint 1.4.0. Please remove the settings from your configuration file(s). Run CFLint in verbose mode for config file location details.

Of course, then there are notes that says:

> * Please note: `inheritPlugins` and `output` were marked deprecated in CFLint 1.2.0 and will be removed in 1.4.0. If you are using `.cflintrc` files now, please remove the inheritPlugins and output properties as soon as possible. Plugin inheritance will going forward always be treated as true since the team cannot see a use case in which it should be disabled. The value of the output attribute is ignored.

So, this ticket is to ask for a better starter example for 1.3.0

As a note, even in 1.2.3 you get the following message with this example `.cflintrc`:

> DEPRECATED: The use of "inheritPlugins" has been marked as deprecated in CFLint 1.2.x and support for it will be fully removed in CFLint 1.3.0. Please remove the setting from your configuration file(s). Run CFLint in verbose mode for config file location details.

**Comment by KamasamaK** [comment]
Addressed by #568
