### ISSUE TITLE
Support for Safe Navigation Operator

### ISSUE THREAD

**Issue by bshea5** [cflint/CFLint#579]
Linter doesn't recognize the Safe Navigation Operator(?.) introduced in CF2016. It throws: [cflint] PARSE_ERROR: Unable to parse.

Here's a link describing the operator: https://www.adobe.com/devnet/coldfusion/articles/language-enhancements-cf-2016.html

**Comment by ryaneberly** [comment]
https://github.com/cfparser/cfparser/issues/103

**Comment by ryaneberly** [comment]
fixed in dev branch.
