### ISSUE TITLE
 MISSING_SEMI with pageencoding 

### ISSUE THREAD

**Issue by jtorz** [cflint/CFLint#580]
I'm getting  the message `[cflint] MISSING_SEMI: End of statement(;) expected after pageencoding`  

```
component {
    pageencoding "UTF-8";
    //...
}
```

**Comment by ryaneberly** [comment]
Is this Lucee only, or ACF as well?

**Comment by ryaneberly** [comment]
It's ACF.
https://helpx.adobe.com/coldfusion/developing-applications/the-cfml-programming-language/extending-coldfusion-pages-with-cfml-scripting/defining-components-and-functions-in-cfscript.html

**Comment by ryaneberly** [comment]
fixed in cfparser, version added to dev branch, test added too
