### ISSUE TITLE
move LOCAL_LITERAL_VALUE_USED_TOO_OFTEN to INFO severity

### ISSUE THREAD

**Issue by natewaite** [cflint/CFLint#584]
I am getting too many false positives with this rule.  And I would argue this rule should be set at a low priority right now it is listed as normal.

**Comment by ryaneberly** [comment]
Moved this and GLOBAL_LITERAL_VALUE_USED_TOO_OFTEN from WARNING to INFO severity.

**Comment by ryaneberly** [comment]
done in dev
