### ISSUE TITLE
Find not english code.

### ISSUE THREAD

**Issue by Vintic** [cflint/CFLint#585]
Hi, how to check if code contains wrong symbol, like 
How to check if code (not value of a variable, and not comment) contains wrong symbol like Russian symbol or any other. 
<cfset vЪr = "hi">

**Comment by TheRealAgentK** [comment]
Does the above code compile and work in Adobe CF and/or Lucee?

If it doesn't compile, I'm not convinced this should be a feature for CFLint. If it does compile then I'm not convinced either - but for a different reason - what'd be an acceptable range of characters then?

**Comment by KamasamaK** [comment]
I agree that CFLint should not have rules for code that does not compile, but I've just verified that the example code does work in ACF.

Regarding what would be an acceptable set of characters, I would say that the regex `[_$a-zA-Z][$\w]*` might be a good start. We could potentially address this request with a proposed solution for #535 which is to validate variable names against a (customizable) regex.
