### ISSUE TITLE
Search unused functions

### ISSUE THREAD

**Issue by Vintic** [cflint/CFLint#586]
How can I search for unused functions in all project.

For example: store all functions initialization in one variable, and all used functions in another, then compare that two lists

**Comment by KamasamaK** [comment]
CFLint only scans each file individually. It would be a big change to track function references across files, and sometimes not even possible to do accurately if using dynamic references such as `createObject("component", somePathToCFC).foo()`.

**Comment by ryaneberly** [comment]
Barring weird scenarios like @KamasamaK mentioned, you could write a plugin that collects a list of all functions and a list of all called functions.    See com.cflint.plugins.core.ArgDefChecker for an example of identifying functions.  

What the framework does not currently provide is a callback when all files are finished processing.

**Comment by KamasamaK** [comment]
I don't think dynamic references are that weird. Even without them, to accurately resolve the component path you would need to know any custom mapping in the server or application configuration and the location of the web root. Assuming the given folder to scan is the web root, it should be easy enough to get the mappings from the application files, but the server mappings would not be available.

**Comment by ryaneberly** [comment]
Good point!

**Comment by ryaneberly** [comment]
On a related note, Unused private functions would be relatively easy.  Is that worth implementing?

**Comment by KamasamaK** [comment]
Private functions would be easier I guess, but be aware that `private` in CFML is equivalent to `protected` in Java, so you would still need to check down the inheritance chain so you'd still have to deal with component path resolution.
