### ISSUE TITLE
Issue with pom.xml file

### ISSUE THREAD

**Issue by sdurette** [cflint/CFLint#59]
After doing a git pull origin master, mvn clean install stops with the error:

[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project  (C:\app\CFLint\pom.xml) has 1 error
[ERROR]     Non-parseable POM C:\app\CFLint\pom.xml: in comment after two dashes (--) next character must be > not \t (p
\n\t\t\t</plugin>\r\n\t on 205 and 218.

The maven clean install will then work.

**Comment by ryaneberly** [comment]
@sdurette Thanks, fixed.
