### ISSUE TITLE
UNUSED_LOCAL_VARIABLE only trigger with var declaration

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#592]
The declaration `var foo = "";` triggers UNUSED_LOCAL_VARIABLE when it is not used, but `local.foo = "";` does not trigger the issue.

**Comment by ryaneberly** [comment]
Good suggestion.  I took a stab at it - give it a whirl

**Comment by KamasamaK** [comment]
It appears to be triggered now based on the few test cases I've run. However, the locations are off. In script functions, it's targeting the scope name instead of the variable name. In tag functions, it's targeting the `cffunction` tag.

**Comment by ryaneberly** [comment]
fixed the line number reporting issues in dev branch.
