### ISSUE TITLE
Parse error for numeric struct keys

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#599]
On the latest 1.5.0 build, I am getting PARSE_ERRORs on numeric struct keys. This does not occur with 1.4.1. 

Even worse, it does it for quoted struct keys, which is recommended in one of the rules.

Here is an example with both

```
<cfset var foo =
	{
		0: "priority",
		5: "status",
		10: "name",
		"abc": "date",
		"xyz": "category"
	}
>
```

**Comment by ryaneberly** [comment]
Thanks.  I did upgrade cfparser - I'll see what the issue is.

**Comment by ryaneberly** [comment]
updated cfparser again, seems to be working with the latest

**Comment by KamasamaK** [comment]
They're not getting PARSE_ERRORs anymore, but now they're getting PLUGIN_ERRORs.

**Comment by ryaneberly** [comment]
Thanks @KamasamaK .  I tried it on the test ParseError\keys_599.cfm  -- and don't see the issue.  Can you help me duplicate it.

**Comment by KamasamaK** [comment]
I cannot reproduce it with your `.cflintrc`, which is probably because it is only including `PARSE_ERROR`.

**Comment by KamasamaK** [comment]
I've rebuilt today and it looks good good now.

**Comment by ryaneberly** [comment]
Thanks @KamasamaK
