### ISSUE TITLE
ValidChars Edit

### ISSUE THREAD

**Issue by Vintic** [cflint/CFLint#601]
Hi, modify please validChars to:
`public boolean validChars(final String name) {
        final Pattern valid = Pattern.compile("^[A-Za-z0-9_#]+$");
        return name.length()==0 || valid.matcher(name).matches();
    }`

Name can be empty, for example in query: 
` <cfquery dbtype="query" name="">`

And name can be with ## symbols.
` <cfquery dbtype="query" name="q_count_total_#q_get_sites.site_id#">`

Where value can be extracted with 
`val(q_count_total_#q_get_sites.site_id#)`

**Comment by ryaneberly** [comment]
fixed in dev
