### ISSUE TITLE
New rule. Query Identity.

### ISSUE THREAD

**Issue by Vintic** [cflint/CFLint#605]
Instead of using @@IDENTITY use SCOPE_IDENTITY() function:
@@IDENTITY returns the last identity value generated for any table in the current session, across all scopes. You need to be careful here, since it's across scopes. You could get a value from a trigger, instead of your current statement.

SCOPE_IDENTITY() returns the last identity value generated for any table in the current session and the current scope. Generally what you want to use.

Found on: https://stackoverflow.com/questions/42648/best-way-to-get-identity-of-inserted-row

**Comment by KamasamaK** [comment]
I don't think this is a good candidate for an included rule since this is for TSQL, not CFML.
