### ISSUE TITLE
VAR_TOO_LONG includes scope

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#608]
```
<cfquery name="variables.getTransactions" datasource="dsn">
	SELECT	*
	FROM	Transactions
</cfquery>
```

The above sample code triggers the VAR_TOO_LONG rule with the message "Variable variables.getTransactions should be shorter than 20 characters." The variable name `getTransactions` is only 15 characters long, but it is also including the scope name which it should not.

**Comment by ryaneberly** [comment]
fixed in dev
