### ISSUE TITLE
-verbose false doesn't work

### ISSUE THREAD

**Issue by jaredbeck** [cflint/CFLint#610]
All of the following produce verbose output:

```
-verbose false
-verbose no
-verbose 0
```

Using `CFLint-1.4.1-all.jar`

**Comment by KamasamaK** [comment]
That switch does not take an argument. Its existence is the only thing checked. See the [wiki page](https://github.com/cflint/CFLint/wiki/How-Do-I-Use-This-Tool%3F) for which switches take an argument.

**Comment by jaredbeck** [comment]
Thanks. The readme says:

> Verbose mode (-verbose <boolean>) enables verbose linting output. 

Maybe we should delete the "<boolean>" part?

**Comment by ryaneberly** [comment]
fixed in dev branch
