### ISSUE TITLE
new Rule, always specify VARCHAR dimension in a Query

### ISSUE THREAD

**Issue by Vintic** [cflint/CFLint#615]
Hi, I think it's a good practice to always specify VARCHAR/NVARCHAR length on CAST and CONVERT.
Because by default it take 30 symbols, that sometimes is not enough.
Correct: CAST(xxxx AS VARCHAR(255))
Wrong: CAST(xxxx AS VARCHAR)

**Comment by bardware** [comment]
That's more an Oracle SQL rule than a CFML rule.

**Comment by Vintic** [comment]
Same thing I was thinking.
But, extracting query from cfm, then provide it to another query checker is hard.
Thanks for reply. I already wrote the rule and will post it tomorrow.

**Comment by Vintic** [comment]
I test it on mssql. The rule It's just a reg expr that search in cfqury content for varchar without parentheses

**Comment by KamasamaK** [comment]
I wouldn't support this as a core rule. But this is why it is extensible so you can add your own rules.

**Comment by Vintic** [comment]
OK, thank you.
That is how I check it:
`@Override
    public void element(final Element element, final Context context, final BugList bugs) {
        final String tagName = element.getName();
        if (tagName.equals(CF.CFQUERY)) {

            String queryGuts = element.getContent().toString();//.replaceAll("\\s+", "");
            queryGuts = queryGuts.toLowerCase();
            Pattern pattern = Pattern.compile("\\b(n?varchar\\s*(.)?)");
            Matcher action_matcher = pattern.matcher(queryGuts);
            int from_index = 0;
            while (action_matcher.find()) {
                String a1 = action_matcher.group(1);
                String a = action_matcher.group(2);
                if(a==null || !action_matcher.group(2).equals("(")){
                    int new_index = queryGuts.indexOf(a1,from_index);
                    int currentline = context.startLine() + countNewLinesUpTo(queryGuts, new_index);
                    from_index = new_index+6;
                    context.addMessage("SQL_VARCHAR_DIMENSION", null,currentline,null);
                }
            }
        }
    }

    public int countNewLinesUpTo(final String val, final int pos) {
        final String x = pos > val.length() ? val : val.substring(0, pos);
        return Math.max(0, x.split("\\R").length - 1);
    }`
