### ISSUE TITLE
Wrong line shows error

### ISSUE THREAD

**Issue by djsanderson** [cflint/CFLint#619]
When using cflint with VS Code, noticed that wrong line number is flagged. This is as of version 1.4.1. Can anything be done to resolve this issue?

**Comment by KamasamaK** [comment]
Can you provide an example? Please include the code and relevant output from the CFLint tool.

**Comment by djsanderson** [comment]
Unfortunately I'm having trouble reproducing this now.  I just had it and after creating a new test file to send to you, it started working properly. Not sure why that would happen.

**Comment by djsanderson** [comment]
I'll close this issue for now and reopen if it happens again.
