### ISSUE TITLE
ERROR in context.getCallStack().checkVariable(name)

### ISSUE THREAD

**Issue by Vintic** [cflint/CFLint#628]
I think context.getCallStack().checkVariable(name) has a bug?

excludes is { "ATTRIBUTES", "SUPER", "CGI", "FORM", ... }
name is "ATTRIBUTES.CFFORMAT"

Code look like:
```
if (excludes.contains(name.toUpperCase())) {
            return true;
}
```

it will never return TRUE
I think need to do something like:

```
String new_name = name.toUpperCase().split("\\.")[0];
    	if (excludes.contains(new_name)) {
            return true;
        }
```

Or I'm doing something wrong? Please help to determine if second parametr is a variable in:
DateTimeFormat(now(), 'dd-mm-yyyy HH:nn:ss')    OR   DateTimeFormat(now(), ATTRIBUTES.CFFORMAT)    OR   DateTimeFormat(now(), cfformat_var)

Variable is extracted in this way:
```
private void check_date_time_format(CFFunctionExpression functionExpression, Context context){
        if ("DateTimeFormat".equalsIgnoreCase(functionExpression.getFunctionName())) {
            final ArrayList<CFExpression> argsExpressions = functionExpression.getArgs();
            if(argsExpressions.size()>1){
                String arg = argsExpressions.get(1).Decompile(0);
```

**Comment by ryaneberly** [comment]
@Vintic . Thanks your suggestion has been applied to dev.
