### ISSUE TITLE
Bug on empty comment

### ISSUE THREAD

**Issue by Vintic** [cflint/CFLint#629]
Bug happens when try
trying to process comment like:

````
"<!--- 1" +
            "<!------------------2------>\n" +
            "<!--- 3 --->\n" +
            "5--->\n" +
            "<!--------------------------->";
````

in CommentReformatting.wrap(String) function.

`com.cflint.exception.CFLintScanException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at com.cflint.CFLint.process(CFLint.java:293)
	at com.cflint.api.CFLintAPI.scan(CFLintAPI.java:83)
`

**Comment by Vintic** [comment]
That how I fixed it:
`if (!stack.isEmpty()) {
                    int en_start = endpos;
                    int en_end = endpos + 4;
                    while (sb.charAt(en_start-1)=='-'){
                        en_start--;
                    }
                    int st_start = pos;
                    int st_end = pos + 3;
                    while (sb.charAt(st_end+1)=='-'){
                        st_end++;
                    }
                    st_end++;
                    if(en_start<=st_end){
                        sb.replace(st_start, en_end, "");
                    }else {
                        sb.replace(en_start, en_end, "-->");
                        sb.replace(st_start, st_end, "<!--");
                    }
                    pos = stack.pop();
                    continue;
                }`

**Comment by ryaneberly** [comment]
Thanks for the fix.  @Vintic, I don't understand the code, but I trust the results  :).  And regressions pass.
