### ISSUE TITLE
Problem with dynamic table and field names

### ISSUE THREAD

**Issue by laserbyte** [cflint/CFLint#65]
I have some queries like the following where the same operation needs to be done on multiple tables so the table name or field name is a variable.

    <cfquery name="queryName" datasource="#datasourceName#">
        update #tableName#
        set fieldName = 'foo';
    </cfqeuery>

However this throws an error like this:

    <cfquery name="#tableName#"> should use <cfqueryparam/> for security reasons.

How can I work around this?

**Comment by jerronjames** [comment]
It's looking for for a parameter type. However, if you do not want it to display, I would suggest setting up a config file https://github.com/cflint/CFLint/wiki/Include-Exclude-Rules-Using-Exteral-XML-File

**Comment by ryaneberly** [comment]
It should say:

    <cfquery name="#queryName#"> should use <cfqueryparam/> for security reasons.

Not tableName.  This is fixed.

**Comment by ryaneberly** [comment]
You can add it to etc/cflintexclude.json as well.
[
 {code:"CFQUERYPARAM_REQ"},    <--- universally disable that code
 {code:"CFQUERYPARAM_REQ", file:"/some/path/to/cfc.cfc"},    <--- disable that code within the file
 {code:"CFQUERYPARAM_REQ", file:"/some/path/to/cfc.cfc", line:"30"},    <--- disable that specific code on that line of the file.
]

**Comment by laserbyte** [comment]
Where do I need to put cflintexclude.json?

In [#25](https://github.com/cflint/CFLint/issues/25) you stated that it "looks for cflintexclude.json anywhere on the classpath" but I have been unable to get that to work:

    export CLASSPATH=${CLASSPATH}:.

I've tried putting it here

    /etc/cflintexclude.json

as well as the same directory as the cflint binary and the same directory as the file I'm scanning but it doesn't appear to be picking it up.

**Comment by ryaneberly** [comment]
the period in 
export CLASSPATH=${CLASSPATH}:.
says to look in the directory where the java process is running.

the following:
export CLASSPATH=${CLASSPATH}:/etc:.
or
export CLASSPATH=${CLASSPATH}:/your/path/to/file/folder/:.
should work for you.

my prior post was a bit misleading sorry.  It looks for "/cflintexclude.json" in the classpath.

**Comment by laserbyte** [comment]
This is the contents of my *cflintexclude.json*:

    [
    	{
    		"code": "MISSING_VAR"
    	}
    ]

I have moved my *cflintexclude.json* to the same directory as my cflint binary and exported what I believe is the correct CLASSPATH:

    export CLASSPATH=${CLASSPATH}:/Applications/bin/cflintexclude.json:.
    echo $CLASSPATH
    /Applications/bin/cflintexclude.json:.

However I am still getting errors like this:

    Variable qFlush is not declared with a var statement. Use var or the local scope, or otherwise clarify the scope

**Comment by ryaneberly** [comment]
The format of your file looks correct.
Use

export CLASSPATH=${CLASSPATH}:/Applications/bin

and it will work.

**Comment by laserbyte** [comment]
That doesn't appear to have any effect. This is how I'm running the command:

    cflint -file gatewayTemplate.cfc

**Comment by ryaneberly** [comment]
Thanks. that helps.
It looks like the cflint *nix script resets the CLASSPATH variable.
But since you are running the script:

* It is located in <basedir>/bin, correct?
* And, there is a cflintexclude.json in <basedir>/etc/ ?  If not, but it there, please.  the startup script puts <basedir>/etc on the classpath.


It should be using that one.

**Comment by laserbyte** [comment]
These are the locations I'm using:

    ls /bin/cflint 
    /bin/cflint

    ls /etc/cflintexclude.json 
    /etc/cflintexclude.json

This is the command I'm running just to be sure:

    /bin/cflint -file gatewayTemplate.cfc

This is the contents of my cflintexclude.json:

    cat /etc/cflintexclude.json 
    [
            {
                    "code": "QUERYNEW_DATATYPE",
                    "code": "GLOBAL_VAR",
                    "code": "ARG_DEFAULT_MISSING"
            }
    ]

But I'm still getting errors like these:

    QueryNew statement should specify datatypes.

**Comment by ryaneberly** [comment]
@laserbyte, There needs to be a separate {} for each exclusion.  Try:

    cat /etc/cflintexclude.json 
    [
            {      "code": "QUERYNEW_DATATYPE"
            },
            {      "code": "GLOBAL_VAR"
            },
            {      "code": "ARG_DEFAULT_MISSING"
            }
    ]

**Comment by laserbyte** [comment]
That appears to have no effect.

**Comment by ryaneberly** [comment]
I'm getting back to this.
I checked in a couple changes so that
-verbose 
will tell you more about the cflintexclude.json being used.

Build from source to try it out, or grab the jar here
https://drive.google.com/file/d/0B8KUYT-JUnurSGZuVldKX0kxV00/view?usp=sharing

run
/bin/cflint -verbose -file gatewayTemplate.cfc
and let's see if the file it's using is the one we expected.
