### ISSUE TITLE
Gradle Install

### ISSUE THREAD

**Issue by jjames967** [cflint/CFLint#67]
Anyone opposed to me switching from Maven to Gradle? If we switch to Gradle, a person won't be required to install Maven. However, I could also add Gradle support along with Maven. It may require a little more maintenance with versioning however.

**Comment by ryaneberly** [comment]
I'm not very familiar with maven, but as long as we are still producing
maven artifacts I'm game.

**Comment by jjames967** [comment]
It's gradle, but I'm glad you're on board since I've already started it. It's on the dev branch. I've also started a build server. My plan is to add code coverage and unit tests to the dev branch. If all the tests pass, it will push to the master branch. Then a third Jenkins job will be ran manually to release on maven central. I'm figuring out the details of releasing, but getting close.

On August 16, 2015, at 8:23 PM, ryaneberly <notifications@github.com> wrote:

I'm not very familiar with maven, but as long as we are still producing
maven artifacts I'm game.

**Comment by ryaneberly** [comment]
Right... typo there.  I meant Gradle.  Thanks Jerron

**Comment by jjames967** [comment]
Not sure about the Jenkins' plugins available for Java. I tried Cobertura, but it tried to run the unit tests and failed. Do any of you know of any other plugins to test code coverage? I'll look a bit more. Nothing fancy, just something to fail a Jenkins build if it doesn't meet a threshold. I'll also continue looking into Cobertura as to why the tests are failing. It's giving a "cannot convert integer to iterator" for some reason.

**Comment by sdurette** [comment]
If moving to Gradle, how about a gradle-build-instructions.md file?  I never used maven before and I only use it for cflint, so the build-instructions.md file got me past that, but with gradle I have no idea what to do.

**Comment by jerronjames** [comment]
There will be instructions. However, they won't be as in-depth as the Maven instructions. This is because you won't need to install Gradle to build the project.

**Comment by ryaneberly** [comment]
The travis build is failing on something gradle related.
https://travis-ci.org/cflint/CFLint

**Comment by ryaneberly** [comment]
@jerronjames 
Do you have time to look into this one?

**Comment by justinmclean** [comment]
Hi,

Build on dev looks OK to me. I did make a change the other and added a "chmod +x gradlew” as it seem to be unable; to execute gradlew, hopefully that didn’t break anything.

Justin

**Comment by ryaneberly** [comment]
Travis is building successfully.  I should have checked first.  Thanks Justin
