### ISSUE TITLE
AVOID_EMPTY_FILES message leaving placeholder

### ISSUE THREAD

**Issue by KamasamaK** [cflint/CFLint#670]
Using the command `java -jar CFLint-1.5.0-SNAPSHOT-all.jar -stdin test-empty-template.cfm -q -e -json -stdout` the message for AVOID_EMPTY_FILES is `CF file is empty: ${file}` with the `${file}` placeholder intact. I've also been able to reproduce this using file input and file output.

**Comment by ryaneberly** [comment]
fixed in dev. thanks @KamasamaK

**Comment by KamasamaK** [comment]
Really, I'm not even sure why the file name is part of the message. File paths are already reported for each issue separately from the message.
