### ISSUE TITLE
Function Length Checker In Config vs. Code

### ISSUE THREAD

**Issue by jjames967** [cflint/CFLint#68]
Currently, the function length checker is hard coded with the number of lines to log a violation. This should be included in the config file.

**Comment by justinmclean** [comment]
Added and checked into dev branch. Here's an example config file fragment showing how to set it:

        <rule name="FunctionLengthChecker" className="FunctionLengthChecker">
            <message code="EXCESSIVE_FUNCTION_LENGTH">
                    <severity>WARNING</severity>
            </message>
            <parameter name="length" value="50"/>
        </rule>
