### ISSUE TITLE
Unable to exclude rules

### ISSUE THREAD

**Issue by justinmclean** [cflint/CFLint#71]
Probably an issue at my end but I can't seemed to get exclude rule to work.

For example both of these:
java -jar ./target/CFLint-0.5.0-all.jar  -file test.cfm -text -excludeRule OUTPUT_ATTR
java -jar ./target/CFLint-0.5.0-all.jar  -file test.cfm -text -excludeRule OutputParmMissing

Produce:
Issue
Severity:INFO
Message code:OUTPUT_ATTR
	File:/Users/justinmclean/Downloads/CFLint/test.cfm
	Column:1
	Line:2
		Message:<cffunction name="test"> should have @output='false'
		Variable:'test' in function: 
		Expression:<cffunction name="test">
<cfargument name="xyz" default="123">
</cffunction>

Similar trouble with include rules.

**Comment by ryaneberly** [comment]
@justinmclean, this is fixed in the main branch.

**Comment by jjames967** [comment]
So, this issue was fixed in the main branch after the release and added to the main branch? If that's the case, it seems like I should get my ass in gear and focus on deployment with a single click.

**Comment by ryaneberly** [comment]
Yeah, I should have problem done that in the dev branch. sorry
