### ISSUE TITLE
Gradle Deployment

### ISSUE THREAD

**Issue by jerronjames** [cflint/CFLint#80]
Switching to Gradle needs a way to create artifacts, sign the artifacts, and upload them to Nexus.

**Comment by ryaneberly** [comment]
Especially with the last round of contribs from Justin.  We should look at a release.

Also figure out which of the checkers are enabled by default. (all of them?).

**Comment by justinmclean** [comment]
I have a few more things to contribute on my list tat's work in progress but it can go into this or the next release.

Will need to update the documentation (perhaps we should consider auto generate via java docs?)

**Comment by jjames967** [comment]
I'm looking for a simple way to either release a snapshot or an actual release with a CI system. When I figure that all out, I'll be releasing a snapshot for testing, then do an actual release. Thanks for all the updates Justin. This release will be awesome!

**Comment by ryaneberly** [comment]
Javadocs sound like a good idea, see #62

**Comment by ryaneberly** [comment]
@jjames967 Thanks for looking into a release

**Comment by jerronjames** [comment]
Javadocs was #61. How the Gradle deployment will work, it will automatically compile javadocs into a jar and upload them to the Nexus Repository. Just need the html information inside the source.
