### ISSUE TITLE
Code Coverage: Dev Branch > Deploy

### ISSUE THREAD

**Issue by jjames967** [cflint/CFLint#84]
I would prefer at least 80% code coverage before testing a merge to the master branch automatically. I see Cobertura was added, but I'm not sure how to see the code coverage. So, what is the code coverage? @justinmclean what do I need to do to run cobertura?

**Comment by justinmclean** [comment]
No idea sorry never run it, but each of the rules I've should have decent code coverage, can add tests if more are needed.

**Comment by justinmclean** [comment]
Just worked it out do:
mvn cobertura:cobertura

And then look at
target/site/cobertura/index.html

**Comment by justinmclean** [comment]
All new rules have 95%+ coverage, but we're lacking in coverage in a few older tests.

**Comment by justinmclean** [comment]
ComponentLengthChecker not has 100% coverage.
