### ISSUE TITLE
Release 0.5.1-SNAPSHOT

### ISSUE THREAD

**Issue by jjames967** [cflint/CFLint#97]
I'll be committing the changes so far to the master branch and releasing a SNAPSHOT version of it to the Sonar repo. Please log any issues found separately.

**Comment by justinmclean** [comment]
Do you want me to hold off on new features / merge the current pull requests? Some existing ones require a little clean up but are probably good enough to release.

**Comment by ryaneberly** [comment]
I'm inclined to include them with the exception of
Added rule to check for repeated hard coded values #94.
I would like to discuss that one further.

The others are tested and working.  We can handle cleanup as enhancements.

**Comment by jjames967** [comment]
Already committed to master. If something should be pulled out, please feel free to do so.

**Comment by jjames967** [comment]
I'll wait on releasing the build.

**Comment by ryaneberly** [comment]
Thanks @jjames967
Give me a few minutes.

**Comment by justinmclean** [comment]
I'm good with the (minor) clean up after the release for the next release.

**Comment by ryaneberly** [comment]
Merged justin's contribs except for #94.

release is ready for now. IMO.

**Comment by ryaneberly** [comment]
Fixed a few cfparser issues as well.  Want to do a release there as well?

**Comment by jjames967** [comment]
Snapshot is finally deployed. There were some issues as my gpg signing specs were deleted from my computer, but I'm hoping the cfparser and cflint changes play okay together. They're both released as snapshots.

**Comment by ryaneberly** [comment]
forgive the obvious question, but where are the snapshots deployed?

**Comment by jjames967** [comment]
It's not a dumb question actually. SonaType holds releases inside a separate repo. It doesn't release them to children sites like Maven Central. If pulling from a pom file, you need to specify it's okay to pull from the SNAPSHOT repo.

	<profiles>
		<profile>
			<id>allow-snapshots</id>
			<activation><activeByDefault>true</activeByDefault></activation>
			<repositories>
				<repository>
					<id>snapshots-repo</id>
					<url>https://oss.sonatype.org/content/repositories/snapshots</url>
					<releases><enabled>false</enabled></releases>
					<snapshots><enabled>true</enabled></snapshots>
				</repository>
			</repositories>
		</profile>
	</profiles>

**Comment by jjames967** [comment]
I made a comment in the wiki

**Comment by ryaneberly** [comment]
Thanks!

**Comment by ryaneberly** [comment]
@jjames967  Sorry, there is a bug fix that is a bit glaring under the right cirumstances.  

#105 
this commit:
https://github.com/cflint/CFLint/commit/d2f86bf376d6ca01e4722682af9447889aa87bdd

This should probable be included in the release.

**Comment by justinmclean** [comment]
Hi,
> @jjames967 <https://github.com/jjames967> Sorry, there is a bug fix that is a bit glaring under the right cirumstances.
> 

Except that it should return 1 not return 0. (Test will fail if it returns 0).

Thanks,
Justin

**Comment by ryaneberly** [comment]
@justinmclean .  Ah right.  Thanks!
